import { StyleSheet } from 'react-native';
import { linearTheme as n } from '../../../theme/linearTheme';
import { errorAlpha, warningAlpha, successAlpha, blackAlpha } from '../../../theme/colorUtils';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: n.colors.background },
  flex: { flex: 1 },
  list: { padding: 16, paddingBottom: 40 },
  headerCompact: {
    marginBottom: 12,
  },
  headerTitleCompact: {
    fontSize: 24,
    lineHeight: 30,
  },
  summaryCard: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 12,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: n.spacing.md,
  },
  summaryCopy: {
    flex: 1,
  },
  summaryEyebrow: {
    letterSpacing: 1.1,
  },
  summaryTitle: {
    marginTop: n.spacing.xs,
  },
  summaryText: {
    marginTop: n.spacing.xs,
  },
  summaryPill: {
    backgroundColor: n.colors.primaryTintSoft,
    borderRadius: n.radius.full,
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  summaryMetricsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: n.spacing.md,
  },
  summaryMetricCard: {
    flexGrow: 1,
    minWidth: 110,
    backgroundColor: n.colors.background,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summaryMetricValue: {
    marginBottom: 2,
  },
  summaryMetricLabel: {
    lineHeight: 16,
  },
  askGuruBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: 16,
    marginBottom: 10,
    backgroundColor: n.colors.accent + '12',
    borderWidth: 1,
    borderColor: n.colors.accent + '35',
    borderRadius: n.radius.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  askGuruBannerCopy: {
    flex: 1,
  },
  askGuruBannerTitle: {
    color: n.colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
  },
  askGuruBannerSubtitle: {
    color: n.colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 0,
    marginBottom: 10,
    borderRadius: n.radius.md,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minHeight: 44,
    gap: 8,
  },
  quickActionsSection: {
    marginTop: 10,
  },
  quickActionsContent: {
    gap: 8,
    paddingRight: 4,
  },
  quickActionChip: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: n.colors.surface,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  quickActionChipPrimary: {
    backgroundColor: n.colors.accent + '10',
    borderColor: n.colors.accent + '35',
  },
  quickActionChipWarning: {
    backgroundColor: n.colors.warning + '10',
    borderColor: n.colors.warning + '30',
  },
  quickActionChipError: {
    backgroundColor: n.colors.error + '10',
    borderColor: n.colors.error + '30',
  },
  quickActionText: {
    color: n.colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  quickActionTextPrimary: {
    color: n.colors.accent,
  },
  quickActionTextWarning: {
    color: n.colors.warning,
  },
  quickActionTextError: {
    color: n.colors.error,
  },
  quickActionValue: {
    color: n.colors.textPrimary,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
  },
  toolbarCard: {
    marginHorizontal: 16,
    marginBottom: 12,
  },
  toolbarHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  toolbarCopy: {
    flex: 1,
  },
  toolbarTitle: {
    fontWeight: '700',
  },
  toolbarSubtitle: {
    marginTop: 2,
  },
  toolbarPill: {
    backgroundColor: n.colors.primaryTintSoft,
    borderRadius: n.radius.full,
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterSection: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  filterTrigger: {
    minHeight: 48,
    borderRadius: n.radius.md,
    backgroundColor: n.colors.surface,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  filterTriggerActive: {
    borderColor: n.colors.accent + '55',
    backgroundColor: n.colors.accent + '10',
  },
  filterTriggerCopy: {
    flex: 1,
    minWidth: 0,
  },
  filterTriggerLabel: {
    color: n.colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  filterTriggerValue: {
    color: n.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    marginTop: 2,
  },
  searchInput: {
    flex: 1,
    color: n.colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    minWidth: 0,
    padding: 0,
  },
  sortSection: {
    marginTop: 10,
  },
  sortTrigger: {
    minHeight: 44,
    borderRadius: n.radius.md,
    backgroundColor: n.colors.surface,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sortTriggerActive: {
    borderColor: n.colors.accent + '55',
    backgroundColor: n.colors.accent + '10',
  },
  sortTriggerLabel: {
    color: n.colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  sortTriggerValueWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  sortTriggerValue: {
    color: n.colors.accent,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
  },
  sortMenu: {
    marginTop: 8,
    borderRadius: n.radius.md,
    backgroundColor: n.colors.surface,
    borderWidth: 1,
    borderColor: n.colors.border,
    overflow: 'hidden',
  },
  sortOption: {
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sortOptionActive: {
    backgroundColor: n.colors.accent + '12',
  },
  sortOptionText: {
    color: n.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  sortOptionTextActive: {
    color: n.colors.accent,
    fontWeight: '700',
  },
  card: {
    backgroundColor: n.colors.surface,
    borderRadius: n.radius.md,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  cardSelected: {
    borderColor: n.colors.accent,
    backgroundColor: n.colors.accent + '12',
  },
  selectIcon: { position: 'absolute', top: 10, right: 10, zIndex: 2 },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  subjectChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexShrink: 1,
    overflow: 'visible',
  },
  dateRow: {
    width: '100%',
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  dateText: {
    color: n.colors.textMuted,
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'right',
    minWidth: 72,
  },
  titleText: {
    color: n.colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 22,
    marginBottom: 8,
  },
  topicsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    gap: 4,
    marginBottom: 8,
  },
  topicPill: {
    backgroundColor: n.colors.surface,
    color: n.colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: n.colors.border,
    overflow: 'hidden',
  },
  moreBadge: {
    color: n.colors.textMuted,
    fontSize: 12,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  confidenceBadge: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    overflow: 'hidden',
  },
  confidenceBadgeLight: {
    color: n.colors.error,
    backgroundColor: errorAlpha['8'],
    borderColor: n.colors.error + '55',
  },
  confidenceBadgeMid: {
    color: n.colors.warning,
    backgroundColor: warningAlpha['8'],
    borderColor: n.colors.warning + '55',
  },
  confidenceBadgeStrong: {
    color: n.colors.success,
    backgroundColor: successAlpha['8'],
    borderColor: n.colors.success + '55',
  },
  wordCount: { color: n.colors.textMuted, fontSize: 12 },
  appBadge: { color: n.colors.textMuted, fontSize: 12 },
  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 48,
    marginTop: 40,
    gap: 16,
  },
  emptyTitle: {
    color: n.colors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtitle: {
    color: n.colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
  loadMoreBtn: {
    alignItems: 'center',
    paddingVertical: 14,
    marginHorizontal: 16,
    marginBottom: 24,
    borderRadius: 12,
    backgroundColor: n.colors.accent + '12',
    borderWidth: 1,
    borderColor: n.colors.accent + '30',
  },
  loadMoreText: {
    color: n.colors.accent,
    fontSize: 14,
    fontWeight: '700',
  },
  cleanupBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: n.colors.error + '12',
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: n.radius.md,
    borderWidth: 1,
    borderColor: n.colors.error + '30',
  },
  dupeBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: n.colors.warning + '12',
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: n.radius.md,
    borderWidth: 1,
    borderColor: n.colors.warning + '30',
  },
  relabelBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: n.colors.accent + '12',
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: n.radius.md,
    borderWidth: 1,
    borderColor: n.colors.accent + '30',
  },
  bannerText: {
    flex: 1,
    color: n.colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    minWidth: 0,
  },
  bannerActionError: { color: n.colors.error, fontSize: 13, lineHeight: 18, fontWeight: '800' },
  bannerActionWarning: {
    color: n.colors.warning,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  bannerActionPrimary: {
    color: n.colors.accent,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  selectionBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    backgroundColor: n.colors.accent + '18',
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: n.radius.md,
    borderWidth: 1,
    borderColor: n.colors.accent + '40',
  },
  selectionText: { color: n.colors.accent, fontSize: 14, lineHeight: 20, fontWeight: '700' },
  selectionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginLeft: 'auto',
  },
  selectionCancelBtn: { paddingHorizontal: 12, paddingVertical: 6 },
  selectionCancelText: {
    color: n.colors.accent,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  selectionDeleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: n.colors.error,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
  },
  selectionDeleteText: {
    color: n.colors.textPrimary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: blackAlpha['45'],
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetCard: {
    backgroundColor: n.colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '82%',
    paddingTop: 12,
    overflow: 'hidden',
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  sheetHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  sheetTitle: {
    color: n.colors.textPrimary,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
  },
  sheetSubtitle: {
    color: n.colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  sheetCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: n.colors.surface,
  },
  clearFiltersBtn: {
    alignSelf: 'flex-start',
    marginHorizontal: 20,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: n.colors.accent + '14',
    borderWidth: 1,
    borderColor: n.colors.accent + '32',
  },
  clearFiltersText: {
    color: n.colors.accent,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  sheetScroll: {
    flexGrow: 0,
  },
  sheetScrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    gap: 20,
  },
  sheetSection: {
    gap: 10,
  },
  sheetSectionTitle: {
    color: n.colors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
  },
  sheetOptions: {
    gap: 8,
  },
  sheetOption: {
    minHeight: 46,
    borderRadius: n.radius.md,
    backgroundColor: n.colors.surface,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sheetOptionActive: {
    borderColor: n.colors.accent + '50',
    backgroundColor: n.colors.accent + '12',
  },
  sheetOptionText: {
    flex: 1,
    minWidth: 0,
    color: n.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  sheetOptionTextActive: {
    color: n.colors.accent,
    fontWeight: '700',
  },
  readerContainer: { flex: 1, backgroundColor: n.colors.background },
  readerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: n.colors.border,
    gap: 10,
  },
  readerCloseBtn: { padding: 6 },
  readerHeaderTitle: {
    flex: 1,
    color: n.colors.textPrimary,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    minWidth: 0,
  },
  readerCopyBtn: { padding: 6 },
  readerScroll: { flex: 1 },
  readerScrollContent: { padding: 20, paddingBottom: 60 },
  readerAskGuruBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 8,
    marginTop: 12,
    marginHorizontal: 16,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: n.colors.accent + '16',
    borderWidth: 1,
    borderColor: n.colors.accent + '35',
  },
  readerAskGuruText: {
    color: n.colors.accent,
    fontSize: 12,
    fontWeight: '800',
  },
  loadingState: { alignItems: 'center', justifyContent: 'center', padding: 48, flex: 1 },
  loadingText: { color: n.colors.textMuted, fontSize: 14, marginTop: 16 },
});

export { n, errorAlpha, warningAlpha, successAlpha, blackAlpha };
