import { StyleSheet } from 'react-native';
import { linearTheme as n } from '../../theme/linearTheme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: n.colors.background },
  screenHeader: { paddingHorizontal: 16, paddingTop: 20, marginBottom: 0 },
  headerCenter: { minWidth: 0 },
  screenHeaderTitle: { fontSize: 22, fontWeight: '800' },
  topicImage: {
    width: '100%',
    height: 180,
    borderRadius: n.radius.md,
    marginBottom: 12,
    backgroundColor: n.colors.card,
  },
  progressRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4, marginBottom: 8 },
  subtitle: { color: n.colors.textSecondary, fontSize: 13 },
  milestoneText: { marginBottom: 8 },
  pctBadge: {
    backgroundColor: n.colors.surfaceHover,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: n.radius.sm,
    marginLeft: 8,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  pctBadgeGood: { backgroundColor: n.colors.successSurface, borderColor: `${n.colors.success}44` },
  pctBadgeComplete: {
    backgroundColor: `${n.colors.warning}18`,
    borderColor: `${n.colors.warning}44`,
  },
  pctText: { color: n.colors.textSecondary, fontWeight: '800', fontSize: 12 },
  progressTrack: {
    height: 4,
    backgroundColor: n.colors.border,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', backgroundColor: n.colors.accent, borderRadius: 2 },
  controls: { paddingHorizontal: 16, gap: 10, marginBottom: 10 },
  searchInputContainer: {},
  searchInput: {
    fontSize: 14,
  },
  singleTopicBanner: {
    borderColor: n.colors.borderHighlight,
  },
  singleTopicBannerTitle: {
    marginBottom: 4,
  },
  singleTopicBannerText: {
    lineHeight: 18,
  },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: n.colors.surface,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  filterChipActive: {
    backgroundColor: n.colors.primaryTintSoft,
    borderColor: `${n.colors.accent}66`,
  },
  filterChipText: { color: n.colors.textSecondary, fontSize: 12, fontWeight: '700' },
  filterChipTextActive: { color: n.colors.accent },
  bulkRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  bulkChip: {
    borderRadius: n.radius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
  },
  bulkDueChip: { backgroundColor: n.colors.errorSurface, borderColor: `${n.colors.error}44` },
  bulkHighYieldChip: {
    backgroundColor: `${n.colors.warning}18`,
    borderColor: `${n.colors.warning}44`,
  },
  bulkWeakChip: { backgroundColor: n.colors.primaryTintSoft, borderColor: `${n.colors.accent}44` },
  bulkChipText: { color: n.colors.textPrimary, fontSize: 12, fontWeight: '800' },
  legend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    paddingBottom: 8,
    gap: 8,
  },
  legendBadge: {},
  list: { paddingHorizontal: 16, paddingBottom: 40 },
  topicRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    overflow: 'hidden',
    borderColor: n.colors.border,
  },
  parentRow: { backgroundColor: n.colors.primaryTintSoft, borderColor: `${n.colors.accent}33` },
  statusBar: { width: 4, alignSelf: 'stretch' },
  topicInfo: { flex: 1, minWidth: 0, padding: 12 },
  nameRow: { flexDirection: 'row', alignItems: 'center', flex: 1, minWidth: 0 },
  folderIcon: { marginRight: 4, marginTop: 1 },
  topicName: {
    color: n.colors.textPrimary,
    fontWeight: '600',
    fontSize: 15,
    lineHeight: 21,
    flex: 1,
  },
  parentName: { fontSize: 16, fontWeight: '800', color: n.colors.accent, flex: 1 },
  parentSummaryRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  parentSummaryText: { color: n.colors.textSecondary, fontSize: 12, fontWeight: '700' },
  parentDueText: { color: n.colors.error, fontSize: 12, fontWeight: '800' },
  parentHighYieldText: { color: n.colors.warning, fontSize: 12, fontWeight: '800' },
  topicMeta: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 4 },
  topicMetaText: { color: n.colors.textSecondary, fontSize: 12, lineHeight: 18 },
  studiedText: { color: n.colors.accent, fontSize: 12, lineHeight: 18 },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  reviewBadge: {
    backgroundColor: n.colors.successSurface,
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: n.radius.sm,
    marginTop: 6,
  },
  reviewOverdue: { backgroundColor: n.colors.errorSurface },
  reviewText: { color: n.colors.success, fontSize: 12, fontWeight: '600' },
  reviewTextOverdue: { color: n.colors.error },
  topicRight: {
    paddingTop: 12,
    paddingRight: 14,
    paddingBottom: 12,
    paddingLeft: 8,
    alignItems: 'stretch',
    minWidth: 104,
    flexShrink: 0,
  },
  confRow: {
    flexDirection: 'row',
    gap: 3,
    marginBottom: 4,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  confLabel: { color: n.colors.textMuted, fontSize: 9, fontWeight: '700', marginRight: 2 },
  confDot: { width: 6, height: 6, borderRadius: 3 },
  statusLabel: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    textAlign: 'right',
    alignSelf: 'flex-end',
    paddingHorizontal: 2,
  },
  notePreview: {
    color: n.colors.accent,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    fontStyle: 'italic',
  },
  emptyContainer: { padding: 40, alignItems: 'center' },
  emptyText: { color: n.colors.textPrimary },
  notesExpanded: {
    marginTop: 6,
    marginBottom: 12,
    borderColor: n.colors.borderHighlight,
  },
  notesExpandedContent: { padding: 12 },
  notesLabel: { color: n.colors.accent, fontWeight: '700', fontSize: 12, marginBottom: 8 },
  notesInput: {
    backgroundColor: n.colors.card,
    borderRadius: n.radius.md,
    padding: 12,
    color: n.colors.textPrimary,
    fontSize: 14,
    minHeight: 80,
    borderWidth: 1,
    borderColor: n.colors.border,
    textAlignVertical: 'top',
    marginBottom: 10,
  },
  imageActionRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  imageActionBtn: {
    flex: 1,
    backgroundColor: n.colors.surface,
    borderRadius: n.radius.md,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  imageActionBtnBusy: {
    opacity: 0.7,
  },
  imageActionBtnText: {
    color: n.colors.accent,
    fontWeight: '700',
    fontSize: 13,
  },
  noteImagesWrap: {
    gap: 8,
    marginBottom: 10,
  },
  noteGeneratedImage: {
    width: '100%',
    height: 220,
    borderRadius: n.radius.md,
    backgroundColor: n.colors.card,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  notesActions: { flexDirection: 'row', gap: 8 },
  notesSave: {
    flex: 1,
    backgroundColor: n.colors.accent,
    borderRadius: n.radius.md,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: `${n.colors.accent}66`,
  },
  notesSaveText: { color: n.colors.textInverse, fontWeight: '700', fontSize: 13 },
  notesCancel: {
    flex: 1,
    backgroundColor: n.colors.surface,
    borderRadius: n.radius.md,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  notesCancelText: { color: n.colors.textSecondary, fontWeight: '600', fontSize: 13 },
  clearCacheBtn: {
    backgroundColor: n.colors.errorSurface,
    borderColor: `${n.colors.error}44`,
    marginTop: 12,
  },
  studyNowBtn: {
    backgroundColor: n.colors.accent,
    borderRadius: n.radius.md,
    padding: 12,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: `${n.colors.accent}66`,
  },
  buttonLoading: {
    opacity: 0.65,
  },
  masteredBtn: {
    backgroundColor: n.colors.success,
    borderColor: `${n.colors.success}66`,
  },
  studyNowText: { color: n.colors.textInverse, fontWeight: '800', fontSize: 14 },
});
