import type { SubjectSeed } from './types';

/**
 * The 19 NEET-PG / INICET subjects. Ids are stable and referenced by
 * `topic_progress`, `topics`, and planning services — do not renumber.
 *
 * Edit weights / colors freely; edit ids only through a DB migration.
 */
export const SUBJECTS_SEED: SubjectSeed[] = [
  {
    id: 1,
    name: 'Anatomy',
    shortCode: 'ANAT',
    colorHex: '#E74C3C',
    inicetWeight: 9,
    neetWeight: 7,
    displayOrder: 1,
  },
  {
    id: 2,
    name: 'Physiology',
    shortCode: 'PHYS',
    colorHex: '#E67E22',
    inicetWeight: 9,
    neetWeight: 6,
    displayOrder: 2,
  },
  {
    id: 3,
    name: 'Biochemistry',
    shortCode: 'BIOC',
    colorHex: '#F1C40F',
    inicetWeight: 8,
    neetWeight: 5,
    displayOrder: 3,
  },
  {
    id: 4,
    name: 'Pathology',
    shortCode: 'PATH',
    colorHex: '#9B59B6',
    inicetWeight: 9,
    neetWeight: 9,
    displayOrder: 4,
  },
  {
    id: 5,
    name: 'Microbiology',
    shortCode: 'MICR',
    colorHex: '#1ABC9C',
    inicetWeight: 8,
    neetWeight: 7,
    displayOrder: 5,
  },
  {
    id: 6,
    name: 'Pharmacology',
    shortCode: 'PHAR',
    colorHex: '#3498DB',
    inicetWeight: 8,
    neetWeight: 8,
    displayOrder: 6,
  },
  {
    id: 7,
    name: 'Forensic Medicine',
    shortCode: 'FMT',
    colorHex: '#95A5A6',
    inicetWeight: 6,
    neetWeight: 5,
    displayOrder: 7,
  },
  {
    id: 8,
    name: 'Medicine',
    shortCode: 'MED',
    colorHex: '#2ECC71',
    inicetWeight: 6,
    neetWeight: 9,
    displayOrder: 8,
  },
  {
    id: 9,
    name: 'Surgery',
    shortCode: 'SURG',
    colorHex: '#27AE60',
    inicetWeight: 5,
    neetWeight: 8,
    displayOrder: 9,
  },
  {
    id: 10,
    name: 'OBG',
    shortCode: 'OBG',
    colorHex: '#E91E63',
    inicetWeight: 5,
    neetWeight: 8,
    displayOrder: 10,
  },
  {
    id: 11,
    name: 'Pediatrics',
    shortCode: 'PEDS',
    colorHex: '#FF9800',
    inicetWeight: 5,
    neetWeight: 7,
    displayOrder: 11,
  },
  {
    id: 12,
    name: 'Orthopedics',
    shortCode: 'ORTH',
    colorHex: '#795548',
    inicetWeight: 4,
    neetWeight: 5,
    displayOrder: 12,
  },
  {
    id: 13,
    name: 'Ophthalmology',
    shortCode: 'OPTH',
    colorHex: '#00BCD4',
    inicetWeight: 5,
    neetWeight: 5,
    displayOrder: 13,
  },
  {
    id: 14,
    name: 'ENT',
    shortCode: 'ENT',
    colorHex: '#607D8B',
    inicetWeight: 5,
    neetWeight: 5,
    displayOrder: 14,
  },
  {
    id: 15,
    name: 'Psychiatry',
    shortCode: 'PSY',
    colorHex: '#673AB7',
    inicetWeight: 4,
    neetWeight: 5,
    displayOrder: 15,
  },
  {
    id: 16,
    name: 'Dermatology',
    shortCode: 'DERM',
    colorHex: '#FF5722',
    inicetWeight: 4,
    neetWeight: 5,
    displayOrder: 16,
  },
  {
    id: 17,
    name: 'Radiology',
    shortCode: 'RADI',
    colorHex: '#9E9E9E',
    inicetWeight: 3,
    neetWeight: 4,
    displayOrder: 17,
  },
  {
    id: 18,
    name: 'Anesthesia',
    shortCode: 'ANES',
    colorHex: '#4CAF50',
    inicetWeight: 3,
    neetWeight: 4,
    displayOrder: 18,
  },
  {
    id: 19,
    name: 'Community Medicine',
    shortCode: 'PSM',
    colorHex: '#388E3C',
    inicetWeight: 7,
    neetWeight: 8,
    displayOrder: 19,
  },
];
