/* global module, require */
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.unit.test.ts', '**/*.unit.test.tsx', '**/*.db.test.ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'json'],
  globals: {
    __DEV__: true,
  },
  maxWorkers: 1,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  testPathIgnorePatterns: ['/node_modules/', '/e2e/'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.unit.test.{ts,tsx}',
    '!src/**/*.db.test.ts',
    '!src/**/__tests__/**',
    '!src/db/testing/**',
    '!src/**/*.d.ts',
  ],
  coveragePathIgnorePatterns: ['/node_modules/', '/e2e/'],
  moduleNameMapper: {
    '^@expo/vector-icons$': '<rootDir>/shims/expo-vector-icons/index.tsx',
    '^react-native-svg$': '<rootDir>/__mocks__/react-native-svg.js',
    '^expo-audio$': '<rootDir>/__mocks__/expo-audio.js',
    '^expo-updates$': '<rootDir>/__mocks__/expo-updates.js',
    '^expo-asset$': '<rootDir>/__mocks__/expo-asset.js',
    '^expo-image$': '<rootDir>/__mocks__/expo-image.js',
    '^expo-network$': '<rootDir>/__mocks__/expo-network.js',
    '^whisper.rn$': '<rootDir>/__mocks__/whisper.rn.js',
    '^whisper\\.rn/index\\.js$': '<rootDir>/__mocks__/whisper.rn.js',
    '^expo-sqlite$': '<rootDir>/__mocks__/expo-sqlite.js',
    '^react-native-pdf$': '<rootDir>/__mocks__/react-native-pdf.js',
    '^react-native-worklets$': '<rootDir>/__mocks__/react-native-worklets.js',
    '^react-native-worklets-core$': '<rootDir>/__mocks__/react-native-worklets.js',
    '^@sentry/react-native$': '<rootDir>/__mocks__/sentry-react-native.js',
    '^react-native-keyboard-controller$': '<rootDir>/__mocks__/react-native-keyboard-controller.js',
    '^@gorhom/bottom-sheet$': '<rootDir>/__mocks__/gorhom-bottom-sheet.js',
    '^@shopify/flash-list$': '<rootDir>/__mocks__/shopify-flash-list.js',
  },
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { configFile: './babel.config.js' }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-runner|@react-native|react-native|@testing-library|react-native-gesture-handler|react-native-reanimated|react-native-css-interop|react-native-markdown-display|react-native-remix-icon|@react-navigation|expo/.*|expo-.*|@expo/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*|jsonrepair)/)',
  ],
};
