import { StyleSheet } from 'react-native';
import { linearTheme as n } from '../../theme/linearTheme';
import { warningAlpha } from '../../theme/colorUtils';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: n.colors.background },
  content: { paddingHorizontal: n.spacing.md, paddingTop: n.spacing.sm, paddingBottom: 40 },
  header: { marginBottom: n.spacing.sm },
  title: { ...n.typography.display, color: n.colors.textPrimary, marginBottom: n.spacing.xs },
  subtitle: { ...n.typography.bodySmall, color: n.colors.textSecondary },
  heroCard: {
    marginBottom: n.spacing.md,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: n.spacing.md,
  },
  heroCopy: {
    flex: 1,
  },
  heroEyebrow: {
    letterSpacing: 1.1,
  },
  heroTitle: {
    marginTop: n.spacing.xs,
  },
  heroText: {
    marginTop: n.spacing.xs,
  },
  heroStatusPill: {
    borderRadius: n.radius.full,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  heroStatusPillOk: {
    backgroundColor: n.colors.successSurface,
    borderColor: `${n.colors.success}55`,
  },
  heroStatusPillWarn: {
    backgroundColor: warningAlpha['12'],
    borderColor: `${n.colors.warning}55`,
  },
  heroContextRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: n.spacing.md,
  },
  heroContextChip: {
    flexGrow: 1,
    minWidth: 132,
    backgroundColor: n.colors.background,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  heroContextValue: {
    marginTop: 2,
  },
  heroHighlightRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: n.spacing.md,
  },
  heroHighlightChip: {
    flexGrow: 1,
    minWidth: 140,
    backgroundColor: n.colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  heroMetricsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: n.spacing.md,
  },
  heroMetricCard: {
    flexGrow: 1,
    minWidth: 110,
    backgroundColor: n.colors.background,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  heroMetricValue: {
    marginBottom: 2,
  },
  heroMetricLabel: {
    lineHeight: 16,
  },
  modeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: n.spacing.sm },
  resourceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 },
  modeChip: {
    backgroundColor: 'transparent',
    borderRadius: n.radius.full,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  modeChipActive: {
    backgroundColor: n.colors.primaryTintSoft,
    borderColor: `${n.colors.accent}66`,
  },
  modeChipText: { ...n.typography.meta, color: n.colors.textMuted, fontWeight: '700' },
  modeChipTextActive: { color: n.colors.textPrimary },
  resourceChip: {
    backgroundColor: 'transparent',
    borderRadius: n.radius.full,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  resourceChipActive: {
    backgroundColor: n.colors.primaryTintSoft,
    borderColor: n.colors.borderLight,
  },
  resourceChipText: { ...n.typography.meta, color: n.colors.textMuted, fontWeight: '700' },
  resourceChipTextActive: { color: n.colors.textPrimary },

  // ── Dashboard card ──
  dashboardCard: {
    marginBottom: n.spacing.md,
  },
  summaryStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: n.spacing.sm,
  },
  summaryCell: { flex: 1, alignItems: 'center' },
  summaryValue: { color: n.colors.textPrimary, fontSize: 18, fontWeight: '900' },
  summaryLabel: { ...n.typography.meta, color: n.colors.textMuted, fontSize: 10, marginTop: 2 },
  summaryDivider: { width: 1, height: 24, backgroundColor: n.colors.border },
  warningHint: {
    ...n.typography.caption,
    color: n.colors.warning,
    marginBottom: n.spacing.sm,
    fontStyle: 'italic',
  },

  // ── Controls row ──
  controlsRow: {
    marginBottom: n.spacing.md,
    gap: n.spacing.sm,
  },

  // ── Section labels ──
  controlCard: {
    marginBottom: 2,
  },
  controlSection: {
    marginBottom: n.spacing.md,
  },
  controlEyebrow: {
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  controlHint: {
    marginBottom: 10,
  },
  sectionTitle: {
    ...n.typography.sectionTitle,
    color: n.colors.textPrimary,
    marginTop: 2,
  },

  dayBlock: {
    marginBottom: n.spacing.md,
    backgroundColor: n.colors.background,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: n.spacing.sm,
    paddingBottom: n.spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: n.colors.border,
    gap: n.spacing.sm,
  },
  dayLabel: { ...n.typography.label, color: n.colors.textPrimary, fontSize: 14 },
  dayMeta: { ...n.typography.meta, color: n.colors.textMuted, textAlign: 'right' },

  topicRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: n.colors.border,
  },
  rowReview: { borderLeftWidth: 2, borderLeftColor: n.colors.success, paddingLeft: 10 },
  rowDeep: { borderLeftWidth: 2, borderLeftColor: n.colors.error, paddingLeft: 10 },
  rowCompleted: { opacity: 0.4 },
  dot: { width: 6, height: 6, borderRadius: 3, marginRight: 10 },
  topicNameRow: { flexDirection: 'row', alignItems: 'center', gap: 5, flexWrap: 'wrap' },
  topicName: { ...n.typography.bodySmall, color: n.colors.textPrimary, fontWeight: '500', flex: 1 },
  topicNameCompleted: { textDecorationLine: 'line-through', color: n.colors.textMuted },
  topicSub: { ...n.typography.meta, color: n.colors.textMuted, fontSize: 11, marginTop: 2 },
  tagReview: {
    ...n.typography.meta,
    fontSize: 10,
    color: n.colors.success,
    fontWeight: '800',
    backgroundColor: n.colors.successSurface,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    overflow: 'hidden',
  },
  tagDeep: {
    ...n.typography.meta,
    fontSize: 10,
    color: n.colors.error,
    fontWeight: '800',
    backgroundColor: n.colors.errorSurface,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    overflow: 'hidden',
  },
  tagNew: {
    ...n.typography.meta,
    fontSize: 10,
    color: n.colors.accent,
    fontWeight: '800',
    backgroundColor: n.colors.primaryTintSoft,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    overflow: 'hidden',
  },
  tagHighYield: {
    ...n.typography.meta,
    fontSize: 10,
    color: n.colors.warning,
    fontWeight: '800',
    backgroundColor: warningAlpha['10'],
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    overflow: 'hidden',
  },
  emptySection: {
    paddingVertical: n.spacing.md,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.background,
    marginBottom: n.spacing.md,
  },
  emptySectionTitle: {
    ...n.typography.bodySmall,
    color: n.colors.textSecondary,
    fontWeight: '600',
  },
  emptySectionSub: { ...n.typography.caption, color: n.colors.textMuted, marginTop: 4 },
  previewMeta: {
    ...n.typography.meta,
    color: n.colors.textMuted,
    marginBottom: 6,
  },

  restBox: {
    padding: n.spacing.sm,
    alignItems: 'center',
    backgroundColor: n.colors.successSurface,
    borderRadius: n.radius.sm,
    marginTop: n.spacing.xs,
  },
  restText: { ...n.typography.caption, color: n.colors.success, fontWeight: '600' },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: n.spacing.lg,
  },
  loadingText: {
    ...n.typography.bodySmall,
    color: n.colors.textSecondary,
    marginTop: 12,
  },
  errorTitle: {
    ...n.typography.sectionTitle,
    color: n.colors.textPrimary,
    marginBottom: n.spacing.sm,
    textAlign: 'center',
  },
  errorText: {
    ...n.typography.bodySmall,
    color: n.colors.textMuted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: n.spacing.md,
  },
  retryButton: {
    backgroundColor: n.colors.accent,
    borderRadius: n.radius.sm,
    paddingHorizontal: 14,
    paddingVertical: n.spacing.sm,
  },
  retryButtonText: {
    ...n.typography.button,
    color: n.colors.textPrimary,
  },
  capacityChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  capacityChip: {
    borderRadius: n.radius.full,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  capacityChipActive: {
    backgroundColor: n.colors.primaryTintSoft,
    borderColor: `${n.colors.accent}88`,
  },
  capacityChipText: { ...n.typography.meta, color: n.colors.textMuted, fontSize: 11 },
  capacityChipTextActive: { color: n.colors.textPrimary },
});

