import { StyleSheet } from 'react-native';
import { linearTheme as n } from '../../theme/linearTheme';
import { blackAlpha } from '../../theme/colorUtils';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: n.colors.background },
  contentArea: { flex: 1, minHeight: 300 },
  storyBarContainer: { height: 3, backgroundColor: n.colors.border },
  storyBarFill: { height: '100%', backgroundColor: n.colors.accent, borderRadius: 0 },
  topicProgressSection: { paddingHorizontal: n.spacing.lg, marginBottom: 8 },
  topicProgressLabel: {
    color: n.colors.textMuted,
    fontSize: 11,
    textAlign: 'right',
    marginBottom: 4,
  },
  topicProgressTrack: {
    height: 3,
    backgroundColor: n.colors.border,
    borderRadius: 1.5,
    overflow: 'hidden',
  },
  topicProgressFill: { height: '100%', backgroundColor: n.colors.accent, borderRadius: 1.5 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: n.spacing.lg,
    paddingVertical: 10,
  },
  headerLeft: { flex: 1, minWidth: 0, marginRight: 12 },
  headerRight: { flexDirection: 'row', alignItems: 'center', paddingTop: 4 },
  topicProgress: { color: n.colors.textSecondary, fontSize: 11, marginBottom: 2 },
  phaseRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  phaseBadge: { marginRight: 2 },
  topicName: { color: n.colors.textPrimary, fontSize: 18, lineHeight: 24, fontWeight: '800' },
  subjectTag: { color: n.colors.accent, fontSize: 12, marginTop: 2 },
  aiSourceLine: {
    color: n.colors.textMuted,
    fontSize: 11,
    marginTop: 6,
    fontWeight: '600',
    lineHeight: 15,
  },
  headerIconButton: {
    backgroundColor: n.colors.card,
    borderRadius: n.radius.md,
    borderWidth: 1,
    borderColor: n.colors.border,
    marginLeft: 6,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 200 },
  menuBackdrop: { flex: 1 },
  menuDropdown: {
    position: 'absolute',
    top: 60,
    right: 16,
    borderRadius: n.radius.md,
    paddingVertical: 4,
    minWidth: 200,
    backgroundColor: n.colors.card,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: n.spacing.lg,
    paddingVertical: 12,
  },
  menuItemEmoji: { fontSize: 16, marginRight: 10 },
  menuItemText: { color: n.colors.textPrimary, fontSize: 14, fontWeight: '600' },
  menuDivider: { height: 1, backgroundColor: n.colors.border, marginHorizontal: 12 },
  contentTypeTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: n.spacing.lg,
    paddingVertical: 8,
    gap: 8,
    backgroundColor: n.colors.background,
  },
  contentTab: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: n.colors.border,
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
  },
  contentTabActive: { backgroundColor: n.colors.accent, borderColor: n.colors.accent },
  contentTabDone: {
    backgroundColor: n.colors.successSurface,
    borderColor: `${n.colors.success}33`,
  },
  contentTabLocked: { opacity: 0.55 },
  contentTabText: { color: n.colors.textPrimary, fontSize: 12, fontWeight: '600' },
  revealScroll: { flexGrow: 1, justifyContent: 'center' },
  revealContainer: { padding: n.spacing.xl },
  revealHeader: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 20 },
  revealHeaderText: { flex: 1 },
  revealTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  revealFocus: { flex: 1 },
  revealMeta: { marginTop: 4 },
  revealModeChip: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    marginTop: 2,
  },
  revealModeChipText: { fontSize: 11, fontWeight: '900', letterSpacing: 0.8 },
  revealGuruCard: {
    borderRadius: n.radius.md,
    padding: n.spacing.lg,
    borderLeftWidth: 3,
    borderLeftColor: n.colors.accent,
    width: '100%',
    marginBottom: 20,
  },
  revealGuruHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  revealGuruLabel: { letterSpacing: 1 },
  revealGuru: { alignSelf: 'stretch' },
  revealSectionLabel: { letterSpacing: 1, marginBottom: 10 },
  revealTopicList: { width: '100%', marginBottom: 20 },
  revealTopic: {
    borderRadius: n.radius.sm,
    borderLeftWidth: 3,
    marginBottom: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  revealTopicRow: { flexDirection: 'row', alignItems: 'center' },
  revealInitial: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  revealInitialText: { fontSize: 13, fontWeight: '800' },
  revealTopicInfo: { flex: 1 },
  revealTopicName: {},
  revealTopicMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 3 },
  revealTopicSub: {},
  revealTopicCards: {},
  revealLiveRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  revealLiveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: n.colors.success },
  revealSub: {},
  topicDoneContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: n.spacing.xl,
  },
  topicDoneName: { marginTop: n.spacing.lg, marginBottom: 12, paddingHorizontal: n.spacing.md },
  topicDoneDivider: {
    width: 40,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: n.colors.success,
    marginBottom: 12,
  },
  topicDoneSub: {},
  topicDoneNext: { marginTop: 16, fontStyle: 'italic' },
  xpPop: { position: 'absolute', top: 16, right: n.spacing.xl },
  xpPopSurface: {
    borderRadius: n.radius.full,
    paddingHorizontal: n.spacing.lg,
    paddingVertical: 8,
    borderColor: `${n.colors.accent}55`,
  },
  xpPopText: { color: n.colors.textPrimary, fontWeight: '900', fontSize: 18 },
  doneContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: n.spacing.xl },
  doneTitle: {
    color: n.colors.textPrimary,
    marginTop: n.spacing.lg,
    marginBottom: n.spacing.xl,
    textAlign: 'center',
  },
  summaryCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: n.spacing.xl,
    width: '100%',
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.card,
  },
  summaryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  summaryItem: { alignItems: 'center' },
  summaryValue: { color: n.colors.textPrimary, fontSize: 28, fontWeight: '900' },
  summaryLabel: { color: n.colors.textSecondary, fontSize: 12, marginTop: 4 },
  summaryDivider: { width: 1, height: 40, backgroundColor: n.colors.border },
  doneStat: { marginBottom: n.spacing.xl, textAlign: 'center' },
  doneBtn: {
    backgroundColor: n.colors.accent,
    borderRadius: 16,
    paddingHorizontal: 40,
    paddingVertical: n.spacing.lg,
  },
  doneBtnText: {
    color: n.colors.textPrimary,
    fontWeight: '800',
    fontSize: 18,
    lineHeight: 24,
    includeFontPadding: false,
  },
  doneSecondaryBtn: {
    borderRadius: 16,
    paddingHorizontal: 40,
    paddingVertical: n.spacing.lg,
    marginTop: 12,
    borderWidth: 1,
    borderColor: n.colors.border,
    width: '100%',
    alignItems: 'center',
  },
  doneSecondaryBtnText: { color: n.colors.textPrimary },
  btnRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  warmupScoreCard: {
    alignItems: 'center',
    marginBottom: 16,
    borderRadius: n.radius.lg,
    paddingVertical: 16,
    paddingHorizontal: 32,
  },
  warmupScoreNumber: { fontSize: 42, fontWeight: '900' },
  warmupScoreFraction: { marginTop: 4 },
  planningContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: n.colors.background,
  },
  planningSubtext: { color: n.colors.textMuted, fontSize: 12, marginTop: 8 },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: n.spacing.xl,
  },
  errorTitle: { color: n.colors.textPrimary, marginTop: 16, marginBottom: 8 },
  errorMsgCard: {
    backgroundColor: n.colors.errorSurface,
    borderRadius: n.radius.md,
    borderTopWidth: 3,
    borderTopColor: n.colors.error,
    padding: n.spacing.lg,
    width: '100%',
    marginBottom: 24,
  },
  errorMsg: { lineHeight: 20 },
  retryBtn: {
    backgroundColor: n.colors.accent,
    borderRadius: 14,
    paddingHorizontal: 40,
    paddingVertical: 14,
    marginBottom: 10,
    width: '100%',
    alignItems: 'center',
  },
  retryBtnText: { color: n.colors.textInverse, fontWeight: '800', fontSize: 16 },
  manualBtn: {
    borderRadius: 14,
    paddingHorizontal: 40,
    paddingVertical: 14,
    marginBottom: 10,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  manualBtnText: { color: n.colors.textPrimary, fontWeight: '800', fontSize: 16 },
  leaveBtn: { paddingVertical: 12, minHeight: 44, justifyContent: 'center' },
  leaveBtnText: { color: n.colors.textMuted, fontSize: 14 },
  guruDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: n.colors.accent,
    shadowColor: n.colors.accent,
    shadowRadius: 6,
    shadowOpacity: 0.9,
    elevation: 4,
    marginRight: 6,
  },
  guruToast: { borderRadius: 12, padding: 12, marginHorizontal: n.spacing.lg, marginBottom: 10 },
  guruToastText: {},
  pausedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: blackAlpha['85'],
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  pausedContent: { alignItems: 'center', paddingHorizontal: 32, width: '100%', maxWidth: 420 },
  pausedText: { marginBottom: 12, textAlign: 'center' },
  pausedSubText: { textAlign: 'center', marginBottom: 32, lineHeight: 22 },
  pausedActions: { flexDirection: 'row', gap: 16 },
  resumeOverlayBtn: {
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: n.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 140,
    justifyContent: 'center',
  },
  resumeBtn: { backgroundColor: n.colors.accent },
  endBtn: { backgroundColor: n.colors.error },
  resumeOverlayBtnText: { color: n.colors.textInverse, fontWeight: '700', fontSize: 16 },
  tabRowWrapper: { flexDirection: 'row', alignItems: 'center', flexGrow: 0, flexShrink: 0 },
  cardCountText: { paddingHorizontal: 10, fontVariant: ['tabular-nums'] },
});
