import { StyleSheet } from 'react-native';
import { linearTheme as n } from '../../theme/linearTheme';
import {
  blackAlpha,
  whiteAlpha,
  captureFillAlpha,
  captureBorderAlpha,
} from '../../theme/colorUtils';

export const s = StyleSheet.create({
  sessionCardShell: {
    flex: 1,
    minHeight: 0,
    marginHorizontal: n.spacing.md,
    marginTop: n.spacing.xs,
    marginBottom: n.spacing.xs,
  },
  sessionCardInner: {
    flex: 1,
    minHeight: 0,
    position: 'relative' as const,
  },
  sessionCardBody: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
  },
  scroll: { flex: 1, minHeight: 0, minWidth: 0 },
  // stretch: default flex-start shrink-wraps children; markdown rows then mis-measure width
  // (last words clipped on Android, esp. landscape with plenty of horizontal space).
  container: {
    padding: 20,
    paddingBottom: 72,
    alignItems: 'stretch' as const,
    flexGrow: 1,
  },
  cardType: {
    color: n.colors.accent,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  inlineLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cardTitle: {
    color: n.colors.textPrimary,
    fontWeight: '800',
    fontSize: 22,
    marginBottom: 20,
    lineHeight: 28,
    minWidth: 0,
    width: '100%',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  topicImage: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    marginBottom: 20,
    backgroundColor: n.colors.surface,
  },
  questionImage: {
    width: '100%',
    height: 220,
    borderRadius: 12,
    marginBottom: 4,
    backgroundColor: n.colors.surface,
  },
  tapToEnlarge: {
    color: n.colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center' as const,
    marginBottom: 14,
  },
  lightboxBackdrop: {
    flex: 1,
    backgroundColor: blackAlpha['92'],
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  pointsContainer: { marginBottom: 16, gap: 10 },
  pointRow: { flexDirection: 'row' as const, marginBottom: 12 },
  bullet: { color: n.colors.accent, fontSize: 16, marginRight: 10, marginTop: 1 },
  pointText: { color: n.colors.textPrimary, fontSize: 15, flex: 1, lineHeight: 22 },
  kpCard: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    alignSelf: 'stretch' as const,
    minWidth: 0,
    backgroundColor: n.colors.surface,
    borderRadius: 12,
    borderLeftWidth: 3,
    padding: 12,
    gap: 10,
  },
  kpNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  kpNumberText: {
    fontSize: 13,
    fontWeight: '800' as const,
  },
  kpContent: {
    flex: 1,
    minWidth: 0,
  },
  kpProgress: {
    color: n.colors.textMuted,
    fontSize: 12,
    fontWeight: '600' as const,
    marginBottom: 12,
  },
  hookBox: {
    backgroundColor: n.colors.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: n.colors.accent + '44',
  },
  hookLabel: {
    color: n.colors.accent,
    fontSize: 11,
    fontWeight: '800' as const,
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  hookText: { color: n.colors.textPrimary, fontSize: 14, fontStyle: 'italic' as const },
  doneBtn: {
    backgroundColor: captureFillAlpha['14'],
    borderWidth: 1,
    borderColor: captureBorderAlpha['24'],
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    marginBottom: 10,
  },
  disabledBtn: { opacity: 0.5 },
  doneBtnText: { color: n.colors.textPrimary, fontWeight: '800', fontSize: 16 },
  skipBtn: { padding: 12, alignItems: 'center' },
  skipText: { color: n.colors.textMuted, fontSize: 13 },
  ratingContainer: { marginTop: 16, marginBottom: 10 },
  ratingTitle: {
    color: n.colors.textSecondary,
    fontSize: 14,
    marginBottom: 12,
    textAlign: 'center',
  },
  ratingRow: { flexDirection: 'row', justifyContent: 'center', gap: 8 },
  ratingBtn: {
    backgroundColor: n.colors.surface,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    minWidth: 56,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  ratingNum: { color: n.colors.textPrimary, fontWeight: '800', fontSize: 18 },
  ratingLabel: { fontSize: 18 },
  questionText: { color: n.colors.textPrimary, fontSize: 16, lineHeight: 24, marginBottom: 16 },
  optionsContainer: { gap: 8, marginBottom: 12 },
  optionBtn: { borderRadius: 12, padding: 14, borderWidth: 2, minWidth: 0 },
  optionText: { color: n.colors.textPrimary, fontSize: 14, lineHeight: 20 },
  iDontKnowBtn: {
    backgroundColor: whiteAlpha['4'],
    borderRadius: 12,
    borderWidth: 1,
    borderColor: n.colors.warning,
    paddingVertical: 14,
    alignItems: 'center' as const,
    marginBottom: 12,
  },
  iDontKnowText: { color: n.colors.warning, fontWeight: '700' as const, fontSize: 15 },
  correctAnswerBox: {
    backgroundColor: `${n.colors.success}1A`,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: n.colors.success,
    padding: 10,
    marginVertical: 8,
  },
  correctAnswerLabel: {
    color: n.colors.success,
    fontSize: 12,
    fontWeight: '700' as const,
    marginBottom: 4,
  },
  correctAnswerText: {
    color: n.colors.textPrimary,
    fontSize: 15,
    fontWeight: '600' as const,
    lineHeight: 22,
  },
  explSection: { marginTop: 8 },
  explSectionTitle: {
    color: n.colors.accent,
    fontSize: 12,
    fontWeight: '700' as const,
    letterSpacing: 0.5,
    marginBottom: 6,
    textTransform: 'uppercase' as const,
  },
  explainDeeperBtn: {
    backgroundColor: captureFillAlpha['10'],
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center' as const,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: n.colors.accent,
  },
  explainDeeperText: { color: n.colors.accent, fontWeight: '700' as const, fontSize: 14 },
  smallExplainBtn: {
    alignSelf: 'flex-start' as const,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: captureFillAlpha['10'],
    borderWidth: 1,
    borderColor: n.colors.accent,
    gap: 4,
  },
  smallExplainText: {
    color: n.colors.accent,
    fontSize: 12,
    fontWeight: '700' as const,
  },
  deepExplLoading: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    padding: 16,
    marginBottom: 12,
    gap: 10,
  },
  deepExplLoadingText: {
    color: n.colors.textSecondary,
    fontSize: 13,
    fontStyle: 'italic' as const,
  },
  explBox: {
    backgroundColor: n.colors.surface,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    minWidth: 0,
    alignSelf: 'stretch' as const,
  },
  explBoxDeep: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  explLabel: {
    color: n.colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
  },
  explText: { color: n.colors.textPrimary, fontSize: 14, lineHeight: 20 },
  markdownBlock: { marginTop: 2 },
  markdownListItem: { marginBottom: 4 },
  storyText: { color: n.colors.textPrimary, fontSize: 15, lineHeight: 26, marginBottom: 20 },
  highlightsBox: {
    backgroundColor: n.colors.surface,
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
  },
  highlightsLabel: {
    color: n.colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
  highlightChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  chip: {
    backgroundColor: `${n.colors.accent}22`,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: `${n.colors.accent}44`,
  },
  chipText: { color: n.colors.accent, fontSize: 12, lineHeight: 18, fontWeight: '600' },
  mnemonicBox: {
    backgroundColor: n.colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: n.colors.accent,
  },
  mnemonicMain: {
    color: n.colors.accent,
    fontWeight: '900',
    fontSize: 28,
    textAlign: 'center',
    letterSpacing: 2,
  },
  expansionList: { marginBottom: 16 },
  expansionLine: { color: n.colors.textPrimary, fontSize: 14, lineHeight: 24, paddingLeft: 8 },
  textInput: {
    backgroundColor: n.colors.surface,
    borderRadius: 12,
    padding: 14,
    color: n.colors.textPrimary,
    fontSize: 15,
    minHeight: 100,
    textAlignVertical: 'top',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  paragraphBox: {
    backgroundColor: n.colors.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  paragraphText: { color: n.colors.textPrimary, fontSize: 15, lineHeight: 24 },
  clueBox: { backgroundColor: n.colors.surface, borderRadius: 12, padding: 14, marginBottom: 8 },
  clueBoxNew: { borderColor: n.colors.accent, borderWidth: 1 },
  clueNum: { color: n.colors.accent, fontSize: 12, fontWeight: '700', marginBottom: 4 },
  clueText: { color: n.colors.textPrimary, fontSize: 15, lineHeight: 22 },
  detectiveActions: { gap: 8, marginTop: 8 },
  hintBtn: { backgroundColor: n.colors.surface, borderWidth: 1, borderColor: n.colors.accent },
  missedBox: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: n.colors.border },
  missedLabel: { color: n.colors.error, fontSize: 12, fontWeight: '700', marginBottom: 4 },
  cardActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  flagBtn: {
    backgroundColor: n.colors.surface,
    borderColor: `${n.colors.warning}44`,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  flagBtnActive: { backgroundColor: `${n.colors.warning}22`, borderColor: n.colors.warning },
  flagBtnText: { color: n.colors.warning, fontWeight: '600', fontSize: 12 },
  askGuruFab: {
    position: 'absolute',
    bottom: 80,
    right: 20,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: n.colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: n.colors.accent,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    zIndex: 10,
  },
  offlineBox: {
    backgroundColor: n.colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  offlineEmoji: { fontSize: 32, textAlign: 'center', marginBottom: 12 },
  offlineText: {
    color: n.colors.textSecondary,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
  promptText: {
    color: n.colors.textPrimary,
    fontSize: 15,
    lineHeight: 28,
    backgroundColor: n.colors.background,
    padding: 20,
    borderRadius: 12,
    marginBottom: 32,
  },
  mkSectionLabel: {
    color: n.colors.textSecondary,
    fontSize: 12,
    fontWeight: '800' as const,
    letterSpacing: 1,
    marginTop: 20,
    marginBottom: 10,
    textTransform: 'uppercase' as const,
  },
  mkList: { gap: 10, marginBottom: 10 },
  mkItem: {
    backgroundColor: n.colors.surface,
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
  },
  mkTipBox: {
    backgroundColor: n.colors.primaryTintSoft,
    borderRadius: 12,
    padding: 16,
    marginTop: 20,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: n.colors.accent + '33',
  },
  mkTipLabel: {
    color: n.colors.accent,
    fontSize: 11,
    fontWeight: '900' as const,
    letterSpacing: 1,
    marginBottom: 6,
  },
  mkTipText: {
    color: n.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'italic' as const,
  },
  flashcardContainer: { flex: 1, padding: 20, justifyContent: 'center', alignItems: 'center' },
  flashcardHeader: { alignSelf: 'flex-start', marginBottom: 12 },
  flashcardEmpty: { textAlign: 'center', marginTop: 16, marginBottom: 24 },
  flashcardBody: {
    width: '100%',
    minHeight: 200,
    backgroundColor: n.colors.surface,
    borderRadius: 20,
    padding: 28,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  flashcardLabel: {
    fontSize: 12,
    fontWeight: '900' as const,
    letterSpacing: 2,
    color: n.colors.textMuted,
    marginBottom: 20,
  },
  flashcardText: {
    color: n.colors.textPrimary,
    fontSize: 20,
    fontWeight: '700' as const,
    textAlign: 'center',
    lineHeight: 30,
  },
  flashcardHint: { marginTop: 20 },
  flashcardActions: { marginTop: 20, width: '100%', alignItems: 'center' },
  flashcardFlipBtn: {
    backgroundColor: n.colors.accent,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 16,
  },
  flashcardFlipText: {
    color: n.colors.textPrimary,
    fontWeight: '800' as const,
    fontSize: 16,
  },
  flashcardDoneBtn: {
    backgroundColor: n.colors.surface,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 16,
  },
  flashcardDoneText: { color: n.colors.textPrimary, fontWeight: '700' as const, fontSize: 16 },
  flashcardNextBtn: {
    backgroundColor: n.colors.accent,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 16,
  },
  flashcardNextText: {
    color: n.colors.textPrimary,
    fontWeight: '800' as const,
    fontSize: 16,
  },
  flashcardRatingRow: {
    flexDirection: 'row',
    gap: 6,
    width: '100%',
  },
  flashcardRatingBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    borderWidth: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flashcardRatingText: {
    fontWeight: '800' as const,
    fontSize: 13,
  },
});

export const FLASHCARD_RATINGS = [
  { label: 'Again', confidence: 0, color: n.colors.error },
  { label: 'Hard', confidence: 1, color: n.colors.warning },
  { label: 'Good', confidence: 2, color: n.colors.success },
  { label: 'Easy', confidence: 3, color: n.colors.accent },
];
