export const SUBJECTS_SEED = [
  { id: 1,  name: 'Anatomy',           shortCode: 'ANAT', colorHex: '#E74C3C', inicetWeight: 9, neetWeight: 7, displayOrder: 1 },
  { id: 2,  name: 'Physiology',        shortCode: 'PHYS', colorHex: '#E67E22', inicetWeight: 9, neetWeight: 6, displayOrder: 2 },
  { id: 3,  name: 'Biochemistry',      shortCode: 'BIOC', colorHex: '#F1C40F', inicetWeight: 8, neetWeight: 5, displayOrder: 3 },
  { id: 4,  name: 'Pathology',         shortCode: 'PATH', colorHex: '#9B59B6', inicetWeight: 9, neetWeight: 9, displayOrder: 4 },
  { id: 5,  name: 'Microbiology',      shortCode: 'MICR', colorHex: '#1ABC9C', inicetWeight: 8, neetWeight: 7, displayOrder: 5 },
  { id: 6,  name: 'Pharmacology',      shortCode: 'PHAR', colorHex: '#3498DB', inicetWeight: 8, neetWeight: 8, displayOrder: 6 },
  { id: 7,  name: 'Forensic Medicine', shortCode: 'FMT',  colorHex: '#95A5A6', inicetWeight: 6, neetWeight: 5, displayOrder: 7 },
  { id: 8,  name: 'Medicine',          shortCode: 'MED',  colorHex: '#2ECC71', inicetWeight: 6, neetWeight: 9, displayOrder: 8 },
  { id: 9,  name: 'Surgery',           shortCode: 'SURG', colorHex: '#27AE60', inicetWeight: 5, neetWeight: 8, displayOrder: 9 },
  { id: 10, name: 'OBG',               shortCode: 'OBG',  colorHex: '#E91E63', inicetWeight: 5, neetWeight: 8, displayOrder: 10 },
  { id: 11, name: 'Pediatrics',        shortCode: 'PEDS', colorHex: '#FF9800', inicetWeight: 5, neetWeight: 7, displayOrder: 11 },
  { id: 12, name: 'Orthopedics',       shortCode: 'ORTH', colorHex: '#795548', inicetWeight: 4, neetWeight: 5, displayOrder: 12 },
  { id: 13, name: 'Ophthalmology',     shortCode: 'OPTH', colorHex: '#00BCD4', inicetWeight: 5, neetWeight: 5, displayOrder: 13 },
  { id: 14, name: 'ENT',               shortCode: 'ENT',  colorHex: '#607D8B', inicetWeight: 5, neetWeight: 5, displayOrder: 14 },
  { id: 15, name: 'Psychiatry',        shortCode: 'PSY',  colorHex: '#673AB7', inicetWeight: 4, neetWeight: 5, displayOrder: 15 },
  { id: 16, name: 'Dermatology',       shortCode: 'DERM', colorHex: '#FF5722', inicetWeight: 4, neetWeight: 5, displayOrder: 16 },
  { id: 17, name: 'Radiology',         shortCode: 'RADI', colorHex: '#9E9E9E', inicetWeight: 3, neetWeight: 4, displayOrder: 17 },
  { id: 18, name: 'Anesthesia',        shortCode: 'ANES', colorHex: '#4CAF50', inicetWeight: 3, neetWeight: 4, displayOrder: 18 },
];

// topic: [subject_id, name, inicet_priority (1-10), estimated_minutes, parent_name (optional)]
export const TOPICS_SEED: [number, string, number, number, string?][] = [
  // ANATOMY (subject 1)
  [1, 'General Anatomy', 7, 30],
  [1, 'Osteology', 6, 40, 'General Anatomy'],
  [1, 'Arthrology', 6, 40, 'General Anatomy'],
  [1, 'Upper Limb', 9, 60],
  [1, 'Brachial Plexus', 10, 45, 'Upper Limb'],
  [1, 'Axillary Artery & Branches', 8, 30, 'Upper Limb'],
  [1, 'Shoulder Joint & Rotator Cuff', 9, 35, 'Upper Limb'],
  [1, 'Elbow Joint & Cubital Fossa', 8, 30, 'Upper Limb'],
  [1, 'Nerves of Upper Limb (Median, Ulnar, Radial)', 10, 45, 'Upper Limb'],
  [1, 'Hand Muscles & Spaces', 9, 40, 'Upper Limb'],
  [1, 'Lower Limb', 9, 60],
  [1, 'Femoral Triangle & Canal', 9, 35, 'Lower Limb'],
  [1, 'Gluteal Region & Sciatic Nerve', 9, 35, 'Lower Limb'],
  [1, 'Popliteal Fossa', 8, 25, 'Lower Limb'],
  [1, 'Knee Joint & Ligaments', 9, 40, 'Lower Limb'],
  [1, 'Ankle Joint & Arches of Foot', 8, 35, 'Lower Limb'],
  [1, 'Thorax', 8, 60],
  [1, 'Mediastinum & Divisions', 8, 30, 'Thorax'],
  [1, 'Heart - External & Internal Features', 10, 45, 'Thorax'],
  [1, 'Lungs & Bronchopulmonary Segments', 9, 40, 'Thorax'],
  [1, 'Diaphragm & Openings', 9, 30, 'Thorax'],
  [1, 'Abdomen & Pelvis', 9, 60],
  [1, 'Anterior Abdominal Wall & Inguinal Canal', 10, 45, 'Abdomen & Pelvis'],
  [1, 'Peritoneum & Greater/Lesser Sac', 9, 40, 'Abdomen & Pelvis'],
  [1, 'Stomach & Blood Supply', 9, 35, 'Abdomen & Pelvis'],
  [1, 'Liver, Gallbladder & Extrahepatic Biliary Apparatus', 10, 45, 'Abdomen & Pelvis'],
  [1, 'Pancreas & Spleen', 8, 30, 'Abdomen & Pelvis'],
  [1, 'Kidneys & Ureters', 9, 35, 'Abdomen & Pelvis'],
  [1, 'Pelvic Organs (Uterus, Bladder, Rectum)', 9, 40, 'Abdomen & Pelvis'],
  [1, 'Perineum & Pudendal Canal', 8, 30, 'Abdomen & Pelvis'],
  [1, 'Head and Neck', 10, 60],
  [1, 'Triangles of Neck (Anterior & Posterior)', 9, 45, 'Head and Neck'],
  [1, 'Thyroid & Parathyroid Glands', 9, 35, 'Head and Neck'],
  [1, 'Salivary Glands (Parotid, Submandibular)', 8, 30, 'Head and Neck'],
  [1, 'Pharynx & Larynx', 9, 45, 'Head and Neck'],
  [1, 'Nasal Cavity & Paranasal Sinuses', 8, 35, 'Head and Neck'],
  [1, 'Tongue & Palate', 8, 30, 'Head and Neck'],
  [1, 'Orbit & Eye Muscles', 9, 40, 'Head and Neck'],
  [1, 'Ear (External, Middle, Internal)', 9, 45, 'Head and Neck'],
  [1, 'Neuroanatomy', 10, 60],
  [1, 'Cerebrum & Functional Areas', 9, 45, 'Neuroanatomy'],
  [1, 'Brainstem (Midbrain, Pons, Medulla)', 10, 50, 'Neuroanatomy'],
  [1, 'Cerebellum', 8, 35, 'Neuroanatomy'],
  [1, 'Thalamus & Hypothalamus', 9, 40, 'Neuroanatomy'],
  [1, 'Basal Ganglia & Limbic System', 9, 40, 'Neuroanatomy'],
  [1, 'Ventricles & CSF Circulation', 10, 35, 'Neuroanatomy'],
  [1, 'Circle of Willis & Blood Supply', 10, 40, 'Neuroanatomy'],
  [1, 'Cranial Nerves (I-XII)', 10, 60, 'Neuroanatomy'],
  [1, 'Spinal Cord & Tracts', 10, 50, 'Neuroanatomy'],
  [1, 'Embryology', 9, 60],
  [1, 'General Embryology (Gametogenesis to Folding)', 9, 45, 'Embryology'],
  [1, 'Development of Heart & Pharyngeal Arches', 10, 50, 'Embryology'],
  [1, 'Development of GI Tract', 9, 40, 'Embryology'],
  [1, 'Development of Renal & Reproductive Systems', 9, 40, 'Embryology'],
  [1, 'Development of Nervous System', 9, 40, 'Embryology'],
  [1, 'Histology', 8, 60],
  [1, 'General Histology (Tissues)', 8, 30, 'Histology'],
  [1, 'Systemic Histology', 8, 45, 'Histology'],

  // PHYSIOLOGY (subject 2)
  [2, 'General Physiology', 8, 40],
  [2, 'Homeostasis & Cell Membrane Transport', 8, 35, 'General Physiology'],
  [2, 'Nerve-Muscle Physiology', 10, 50],
  [2, 'Action Potential & Nerve Conduction', 10, 40, 'Nerve-Muscle Physiology'],
  [2, 'Neuromuscular Junction', 10, 35, 'Nerve-Muscle Physiology'],
  [2, 'Skeletal & Smooth Muscle Contraction', 9, 40, 'Nerve-Muscle Physiology'],
  [2, 'Blood', 9, 60],
  [2, 'Plasma Proteins & Hemoglobin', 8, 35, 'Blood'],
  [2, 'RBCs, Erythropoiesis & Anemias', 10, 45, 'Blood'],
  [2, 'WBCs & Immunity', 9, 40, 'Blood'],
  [2, 'Platelets & Hemostasis (Coagulation)', 10, 45, 'Blood'],
  [2, 'Blood Groups', 8, 30, 'Blood'],
  [2, 'Cardiovascular System (CVS)', 10, 60],
  [2, 'Cardiac Cycle & Heart Sounds', 10, 50, 'Cardiovascular System (CVS)'],
  [2, 'ECG & Arrhythmias', 10, 50, 'Cardiovascular System (CVS)'],
  [2, 'Cardiac Output & Regulation', 10, 45, 'Cardiovascular System (CVS)'],
  [2, 'Blood Pressure & Regulation', 10, 45, 'Cardiovascular System (CVS)'],
  [2, 'Regional Circulation (Coronary, Cerebral, Splanchnic)', 9, 40, 'Cardiovascular System (CVS)'],
  [2, 'Respiratory System', 9, 60],
  [2, 'Mechanics of Breathing (Surfactant, Compliance)', 9, 45, 'Respiratory System'],
  [2, 'Lung Volumes & Capacities', 10, 35, 'Respiratory System'],
  [2, 'Gas Exchange & Transport (O2, CO2)', 10, 45, 'Respiratory System'],
  [2, 'Regulation of Respiration', 9, 40, 'Respiratory System'],
  [2, 'High Altitude & Deep Sea Physiology', 8, 30, 'Respiratory System'],
  [2, 'Excretory System (Renal)', 10, 60],
  [2, 'GFR & Tubular Transport', 10, 45, 'Excretory System (Renal)'],
  [2, 'Countercurrent Mechanism & Urine Concentration', 10, 40, 'Excretory System (Renal)'],
  [2, 'Acid-Base Balance & Buffers', 10, 45, 'Excretory System (Renal)'],
  [2, 'Renal Function Tests', 8, 30, 'Excretory System (Renal)'],
  [2, 'Micturition', 8, 30, 'Excretory System (Renal)'],
  [2, 'Gastrointestinal System (GIT)', 9, 50],
  [2, 'Salivary, Gastric & Pancreatic Secretions', 9, 40, 'Gastrointestinal System (GIT)'],
  [2, 'Liver & Bile', 9, 35, 'Gastrointestinal System (GIT)'],
  [2, 'Digestion & Absorption', 9, 40, 'Gastrointestinal System (GIT)'],
  [2, 'GI Motility', 8, 30, 'Gastrointestinal System (GIT)'],
  [2, 'Endocrine System', 10, 60],
  [2, 'Mechanism of Hormone Action', 9, 35, 'Endocrine System'],
  [2, 'Pituitary Gland & Hypothalamus', 9, 45, 'Endocrine System'],
  [2, 'Thyroid Gland', 10, 40, 'Endocrine System'],
  [2, 'Adrenal Gland (Cortex & Medulla)', 10, 45, 'Endocrine System'],
  [2, 'Calcium Metabolism (PTH, Vitamin D)', 10, 40, 'Endocrine System'],
  [2, 'Pancreatic Hormones (Insulin, Glucagon)', 10, 40, 'Endocrine System'],
  [2, 'Reproductive System', 8, 50],
  [2, 'Male Reproduction', 8, 35, 'Reproductive System'],
  [2, 'Female Reproduction & Menstrual Cycle', 9, 45, 'Reproductive System'],
  [2, 'Central Nervous System (CNS)', 10, 60],
  [2, 'Sensory System & Receptors', 9, 45, 'Central Nervous System (CNS)'],
  [2, 'Motor System & Tracts', 10, 50, 'Central Nervous System (CNS)'],
  [2, 'Reflexes & Muscle Tone', 9, 40, 'Central Nervous System (CNS)'],
  [2, 'Cerebellum & Basal Ganglia', 9, 45, 'Central Nervous System (CNS)'],
  [2, 'Limbic System & Hypothalamus', 8, 35, 'Central Nervous System (CNS)'],
  [2, 'Sleep, EEG & Higher Functions', 8, 40, 'Central Nervous System (CNS)'],
  [2, 'Autonomic Nervous System', 10, 35, 'Central Nervous System (CNS)'],
  [2, 'Special Senses', 9, 50],
  [2, 'Vision (Optics, Retina, Pathways)', 10, 50, 'Special Senses'],
  [2, 'Hearing', 9, 40, 'Special Senses'],
  [2, 'Taste & Smell', 7, 25, 'Special Senses'],

  // BIOCHEMISTRY (subject 3)
  [3, 'Molecular Biology', 10, 60],
  [3, 'DNA Replication & Repair', 10, 45, 'Molecular Biology'],
  [3, 'Transcription & Translation', 10, 50, 'Molecular Biology'],
  [3, 'Gene Regulation & Mutations', 9, 40, 'Molecular Biology'],
  [3, 'Recombinant DNA Technology (PCR, Blotting)', 10, 50, 'Molecular Biology'],
  [3, 'Metabolism of Carbohydrates', 10, 60],
  [3, 'Glycolysis & TCA Cycle', 10, 45, 'Metabolism of Carbohydrates'],
  [3, 'Gluconeogenesis & Glycogen Metabolism', 10, 45, 'Metabolism of Carbohydrates'],
  [3, 'HMP Shunt & Uronic Acid Pathway', 9, 35, 'Metabolism of Carbohydrates'],
  [3, 'Metabolism of Lipids', 10, 60],
  [3, 'Fatty Acid Oxidation & Synthesis', 10, 45, 'Metabolism of Lipids'],
  [3, 'Cholesterol Metabolism & Bile Salts', 9, 40, 'Metabolism of Lipids'],
  [3, 'Lipoprotein Metabolism & Dyslipidemias', 10, 50, 'Metabolism of Lipids'],
  [3, 'Ketone Bodies', 8, 25, 'Metabolism of Lipids'],
  [3, 'Metabolism of Proteins & Amino Acids', 10, 60],
  [3, 'Urea Cycle & Ammonia Transport', 10, 35, 'Metabolism of Proteins & Amino Acids'],
  [3, 'Metabolism of Individual Amino Acids (Phe, Tyr, Trp)', 10, 50, 'Metabolism of Proteins & Amino Acids'],
  [3, 'Heme Metabolism (Synthesis & Porphyrias)', 10, 45, 'Metabolism of Proteins & Amino Acids'],
  [3, 'Enzymes', 9, 50],
  [3, 'Enzyme Kinetics (Km, Vmax)', 10, 40, 'Enzymes'],
  [3, 'Inhibition & Regulation', 9, 35, 'Enzymes'],
  [3, 'Biological Oxidation (ETC)', 10, 45],
  [3, 'Vitamins & Minerals', 9, 60],
  [3, 'Fat-Soluble Vitamins (A, D, E, K)', 10, 45, 'Vitamins & Minerals'],
  [3, 'Water-Soluble Vitamins (B-complex, C)', 10, 50, 'Vitamins & Minerals'],
  [3, 'Major Minerals (Ca, P, Mg)', 9, 35, 'Vitamins & Minerals'],
  [3, 'Trace Elements', 8, 30, 'Vitamins & Minerals'],

  // PATHOLOGY (subject 4)
  [4, 'General Pathology', 10, 60],
  [4, 'Cell Injury, Death & Apoptosis', 10, 50, 'General Pathology'],
  [4, 'Acute & Chronic Inflammation', 10, 45, 'General Pathology'],
  [4, 'Hemodynamic Disorders (Edema, Shock, Thrombosis)', 10, 50, 'General Pathology'],
  [4, 'Genetics & Metabolic Disorders', 9, 45, 'General Pathology'],
  [4, 'Immunopathology (Hypersensitivity, Autoimmunity)', 10, 50, 'General Pathology'],
  [4, 'Neoplasia (Oncogenes, Markers, Staging)', 10, 60, 'General Pathology'],
  [4, 'Hematology', 10, 60],
  [4, 'Anemias (Microcytic, Macrocytic, Hemolytic)', 10, 55, 'Hematology'],
  [4, 'WBC Disorders & Leukemias', 10, 60, 'Hematology'],
  [4, 'Lymphomas (Hodgkin & Non-Hodgkin)', 10, 50, 'Hematology'],
  [4, 'Multiple Myeloma', 9, 35, 'Hematology'],
  [4, 'Platelet & Coagulation Disorders', 10, 45, 'Hematology'],
  [4, 'Blood Transfusion', 8, 30, 'Hematology'],
  [4, 'Systemic Pathology', 10, 60],
  [4, 'Cardiovascular Pathology (MI, RHD)', 10, 50, 'Systemic Pathology'],
  [4, 'Respiratory Pathology (COPD, Pneumonia, Lung Ca)', 10, 50, 'Systemic Pathology'],
  [4, 'GI & Liver Pathology (Cirrhosis, Hepatitis, IBD)', 10, 55, 'Systemic Pathology'],
  [4, 'Renal Pathology (Glomerulonephritis, Tumors)', 10, 50, 'Systemic Pathology'],
  [4, 'Endocrine Pathology (Thyroid, Adrenal, Diabetes)', 10, 45, 'Systemic Pathology'],
  [4, 'Male & Female Genital Tract Pathology', 9, 50, 'Systemic Pathology'],
  [4, 'Breast Pathology', 9, 35, 'Systemic Pathology'],
  [4, 'CNS Pathology', 9, 40, 'Systemic Pathology'],
  [4, 'Bone & Soft Tissue Pathology', 8, 35, 'Systemic Pathology'],

  // MICROBIOLOGY (subject 5)
  [5, 'General Microbiology', 9, 50],
  [5, 'Sterilization & Disinfection', 10, 40, 'General Microbiology'],
  [5, 'Bacterial Morphology & Physiology', 8, 35, 'General Microbiology'],
  [5, 'Immunology', 10, 60],
  [5, 'Antigen, Antibody & Complement', 10, 45, 'Immunology'],
  [5, 'Immune Response & MHC', 10, 40, 'Immunology'],
  [5, 'Hypersensitivity & Autoimmunity', 10, 40, 'Immunology'],
  [5, 'Systemic Bacteriology', 10, 60],
  [5, 'Staphylococcus & Streptococcus', 10, 50, 'Systemic Bacteriology'],
  [5, 'Neisseria & Corynebacterium', 9, 40, 'Systemic Bacteriology'],
  [5, 'Bacillus & Clostridium', 10, 45, 'Systemic Bacteriology'],
  [5, 'Enterobacteriaceae (Salmonella, Shigella)', 10, 55, 'Systemic Bacteriology'],
  [5, 'Vibrio & Pseudomonas', 9, 35, 'Systemic Bacteriology'],
  [5, 'Mycobacteria (TB & Leprosy)', 10, 50, 'Systemic Bacteriology'],
  [5, 'Spirochetes', 9, 35, 'Systemic Bacteriology'],
  [5, 'Rickettsia, Chlamydia & Mycoplasma', 9, 40, 'Systemic Bacteriology'],
  [5, 'Virology', 10, 60],
  [5, 'General Virology', 9, 35, 'Virology'],
  [5, 'Hepatitis Viruses', 10, 45, 'Virology'],
  [5, 'HIV/AIDS', 10, 40, 'Virology'],
  [5, 'Herpes Viruses', 10, 40, 'Virology'],
  [5, 'Myxoviruses (Influenza, Measles)', 9, 40, 'Virology'],
  [5, 'Arboviruses (Dengue, Japanese Encephalitis)', 9, 35, 'Virology'],
  [5, 'Parasitology', 10, 60],
  [5, 'Protozoology (Amoeba, Malaria, Leishmania)', 10, 55, 'Parasitology'],
  [5, 'Helminthology (Ascaris, Hookworm, Tapeworms)', 10, 50, 'Parasitology'],
  [5, 'Mycology', 9, 40],
  [5, 'Superficial & Deep Mycoses', 9, 35, 'Mycology'],
  [5, 'Opportunistic Fungi (Candida, Aspergillus)', 10, 35, 'Mycology'],

  // PHARMACOLOGY (subject 6)
  [6, 'General Pharmacology', 10, 50],
  [6, 'Pharmacokinetics (ADME)', 10, 45, 'General Pharmacology'],
  [6, 'Pharmacodynamics (Receptors)', 10, 40, 'General Pharmacology'],
  [6, 'Autonomic Nervous System (ANS)', 10, 60],
  [6, 'Cholinergic & Anticholinergic Drugs', 10, 50, 'Autonomic Nervous System (ANS)'],
  [6, 'Adrenergic & Antiadrenergic Drugs', 10, 50, 'Autonomic Nervous System (ANS)'],
  [6, 'Skeletal Muscle Relaxants', 9, 30, 'Autonomic Nervous System (ANS)'],
  [6, 'Central Nervous System (CNS)', 10, 60],
  [6, 'Sedatives, Hypnotics & Alcohol', 9, 40, 'Central Nervous System (CNS)'],
  [6, 'Antiepileptics', 10, 45, 'Central Nervous System (CNS)'],
  [6, 'Antipsychotics & Antidepressants', 10, 50, 'Central Nervous System (CNS)'],
  [6, 'Drugs for Parkinsonism', 9, 35, 'Central Nervous System (CNS)'],
  [6, 'Opioid Analgesics', 10, 40, 'Central Nervous System (CNS)'],
  [6, 'Local & General Anesthetics', 9, 45, 'Central Nervous System (CNS)'],
  [6, 'Autacoids & Respiratory System', 9, 50],
  [6, 'NSAIDs & Gout Drugs', 10, 45, 'Autacoids & Respiratory System'],
  [6, 'Drugs for Asthma & COPD', 10, 40, 'Autacoids & Respiratory System'],
  [6, 'Cardiovascular System (CVS)', 10, 60],
  [6, 'Diuretics', 10, 40, 'Cardiovascular System (CVS)'],
  [6, 'Antihypertensives', 10, 50, 'Cardiovascular System (CVS)'],
  [6, 'Drugs for Heart Failure & Angina', 10, 50, 'Cardiovascular System (CVS)'],
  [6, 'Antiarrhythmics', 10, 45, 'Cardiovascular System (CVS)'],
  [6, 'Hypolipidemic Drugs', 9, 35, 'Cardiovascular System (CVS)'],
  [6, 'Renal & Blood Pharmacology', 10, 50],
  [6, 'Hematinics & Coagulants', 9, 40, 'Renal & Blood Pharmacology'],
  [6, 'Anticoagulants & Fibrinolytics', 10, 45, 'Renal & Blood Pharmacology'],
  [6, 'Endocrine Pharmacology', 10, 60],
  [6, 'Insulin & Oral Hypoglycemics', 10, 50, 'Endocrine Pharmacology'],
  [6, 'Thyroid & Antithyroid Drugs', 9, 35, 'Endocrine Pharmacology'],
  [6, 'Corticosteroids', 10, 40, 'Endocrine Pharmacology'],
  [6, 'Estrogens, Progestins & Contraceptives', 10, 45, 'Endocrine Pharmacology'],
  [6, 'Chemotherapy', 10, 60],
  [6, 'General Principles & Beta-lactams', 10, 45, 'Chemotherapy'],
  [6, 'Aminoglycosides, Macrolides, Tetracyclines', 10, 50, 'Chemotherapy'],
  [6, 'Fluoroquinolones & Sulfonamides', 9, 40, 'Chemotherapy'],
  [6, 'Antitubercular & Antileprotic Drugs', 10, 50, 'Chemotherapy'],
  [6, 'Antifungal, Antiviral & Antimalarial Drugs', 10, 55, 'Chemotherapy'],
  [6, 'Anticancer Drugs', 10, 50, 'Chemotherapy'],
  [6, 'Miscellaneous', 9, 40],
  [6, 'Gastrointestinal Drugs', 9, 40, 'Miscellaneous'],
  [6, 'Drug Toxicity & Antidotes', 10, 35, 'Miscellaneous'],

  // MEDICINE (subject 8)
  [8, 'Infectious Diseases', 10, 60],
  [8, 'Tuberculosis', 10, 50, 'Infectious Diseases'],
  [8, 'HIV/AIDS & Opportunistic Infections', 10, 55, 'Infectious Diseases'],
  [8, 'Malaria, Kala-azar, Enteric Fever', 10, 50, 'Infectious Diseases'],
  [8, 'Sepsis & Tropical Fevers', 9, 45, 'Infectious Diseases'],
  [8, 'Cardiology', 10, 60],
  [8, 'Heart Failure', 10, 45, 'Cardiology'],
  [8, 'Valvular Heart Diseases', 10, 50, 'Cardiology'],
  [8, 'Ischemic Heart Disease (ACS)', 10, 55, 'Cardiology'],
  [8, 'Hypertension', 10, 40, 'Cardiology'],
  [8, 'Congenital Heart Diseases (Adult)', 9, 35, 'Cardiology'],
  [8, 'Rheumatology', 10, 50],
  [8, 'Rheumatoid Arthritis & Osteoarthritis', 10, 45, 'Rheumatology'],
  [8, 'SLE & Vasculitis', 10, 50, 'Rheumatology'],
  [8, 'Seronegative Spondyloarthropathies', 9, 35, 'Rheumatology'],
  [8, 'Nephrology', 10, 60],
  [8, 'Acute & Chronic Kidney Disease', 10, 50, 'Nephrology'],
  [8, 'Glomerular Diseases', 10, 45, 'Nephrology'],
  [8, 'Electrolyte & Acid-Base Disorders', 10, 50, 'Nephrology'],
  [8, 'Neurology', 10, 60],
  [8, 'Stroke & TIA', 10, 50, 'Neurology'],
  [8, 'Epilepsy & Seizures', 10, 45, 'Neurology'],
  [8, 'Demyelinating Diseases (Multiple Sclerosis)', 9, 40, 'Neurology'],
  [8, 'Movement Disorders (Parkinsonism)', 9, 40, 'Neurology'],
  [8, 'Dementia & Coma', 9, 40, 'Neurology'],
  [8, 'Spinal Cord & Peripheral Nerve Disorders', 9, 45, 'Neurology'],
  [8, 'Endocrinology', 10, 60],
  [8, 'Diabetes Mellitus', 10, 55, 'Endocrinology'],
  [8, 'Thyroid Disorders', 10, 45, 'Endocrinology'],
  [8, 'Adrenal & Pituitary Disorders', 10, 50, 'Endocrinology'],
  [8, 'Gastroenterology & Hepatology', 10, 60],
  [8, 'Peptic Ulcer & IBD', 10, 45, 'Gastroenterology & Hepatology'],
  [8, 'Cirrhosis & Portal Hypertension', 10, 50, 'Gastroenterology & Hepatology'],
  [8, 'Hepatitis & Pancreatitis', 10, 45, 'Gastroenterology & Hepatology'],
  [8, 'Hematology (Clinical)', 10, 50],
  [8, 'Anemias, Leukemias & Lymphomas', 10, 55, 'Hematology (Clinical)'],

  // SURGERY (subject 9)
  [9, 'General Surgery', 10, 60],
  [9, 'Shock, Hemorrhage & Fluid Management', 10, 50, 'General Surgery'],
  [9, 'Wound Healing & Surgical Infections', 9, 40, 'General Surgery'],
  [9, 'Burns & Resuscitation', 9, 40, 'General Surgery'],
  [9, 'Trauma (ATLS Principles)', 10, 50, 'General Surgery'],
  [9, 'Systemic Surgery', 10, 60],
  [9, 'Thyroid & Parathyroid Surgery', 10, 45, 'Systemic Surgery'],
  [9, 'Breast Diseases & Cancer', 10, 50, 'Systemic Surgery'],
  [9, 'Esophagus & Stomach Surgery', 10, 50, 'Systemic Surgery'],
  [9, 'Small & Large Intestine (Obstruction, Ca)', 10, 55, 'Systemic Surgery'],
  [9, 'Liver, Gallbladder & Bile Duct Surgery', 10, 55, 'Systemic Surgery'],
  [9, 'Hernias (Inguinal, Incisional)', 10, 40, 'Systemic Surgery'],
  [9, 'Ano-rectal Disorders', 9, 35, 'Systemic Surgery'],
  [9, 'Urology (Surgery)', 10, 60],
  [9, 'Renal Calculi & Tumors', 10, 50, 'Urology (Surgery)'],
  [9, 'Prostate (BPH, Ca)', 10, 45, 'Urology (Surgery)'],
  [9, 'Scrotal Swellings', 9, 35, 'Urology (Surgery)'],

  // OBG (subject 10)
  [10, 'Obstetrics', 10, 60],
  [10, 'Normal Pregnancy & Antenatal Care', 10, 45, 'Obstetrics'],
  [10, 'Normal Labor & Partogram', 10, 50, 'Obstetrics'],
  [10, 'Pre-eclampsia & Eclampsia', 10, 45, 'Obstetrics'],
  [10, 'Antepartum & Postpartum Hemorrhage', 10, 55, 'Obstetrics'],
  [10, 'Medical Disorders in Pregnancy (Anemia, Diabetes)', 10, 50, 'Obstetrics'],
  [10, 'Multiple Pregnancy & Rh Isoimmunization', 9, 40, 'Obstetrics'],
  [10, 'Fetal Monitoring', 9, 35, 'Obstetrics'],
  [10, 'Gynecology', 10, 60],
  [10, 'Menstrual Disorders (DUB, PCOS)', 10, 50, 'Gynecology'],
  [10, 'Infertility & ART', 10, 50, 'Gynecology'],
  [10, 'Contraception', 10, 45, 'Gynecology'],
  [10, 'Genital Prolapse', 9, 35, 'Gynecology'],
  [10, 'Gynae-Oncology (Cervix, Uterus, Ovary)', 10, 60, 'Gynecology'],

  // PEDIATRICS (subject 11)
  [11, 'General Pediatrics', 10, 50],
  [11, 'Growth & Development', 10, 50, 'General Pediatrics'],
  [11, 'Nutrition & Malnutrition', 10, 45, 'General Pediatrics'],
  [11, 'Immunization & Infections', 10, 50, 'General Pediatrics'],
  [11, 'Genetics & Metabolic Disorders', 9, 40, 'General Pediatrics'],
  [11, 'Fluids & Electrolytes', 9, 35, 'General Pediatrics'],
  [11, 'Systemic Pediatrics', 10, 60],
  [11, 'Neonatology', 10, 60, 'Systemic Pediatrics'],
  [11, 'Pediatric Cardiology (CHD)', 10, 50, 'Systemic Pediatrics'],
  [11, 'Pediatric Respiratory Disorders', 10, 45, 'Systemic Pediatrics'],
  [11, 'Pediatric Nephrology', 10, 45, 'Systemic Pediatrics'],
  [11, 'Pediatric Neurology & Epilepsy', 10, 50, 'Systemic Pediatrics'],
  [11, 'Pediatric GI & Hepatology', 9, 40, 'Systemic Pediatrics'],
  [11, 'Pediatric Hematology & Oncology', 9, 45, 'Systemic Pediatrics'],
  [11, 'Pediatric Endocrinology', 9, 40, 'Systemic Pediatrics'],

  // ORTHOPEDICS (subject 12)
  [12, 'Traumatology', 10, 60],
  [12, 'Fracture Healing & Complications', 10, 40, 'Traumatology'],
  [12, 'Upper Limb Fractures & Dislocations', 10, 50, 'Traumatology'],
  [12, 'Lower Limb Fractures & Dislocations', 10, 50, 'Traumatology'],
  [12, 'Spine & Pelvis Trauma', 10, 45, 'Traumatology'],
  [12, 'Peripheral Nerve Injuries', 9, 35, 'Traumatology'],
  [12, 'Orthopedic Diseases', 9, 60],
  [12, 'Bone Infections (Osteomyelitis, TB)', 10, 50, 'Orthopedic Diseases'],
  [12, 'Bone Tumors', 10, 45, 'Orthopedic Diseases'],
  [12, 'Metabolic Bone Diseases (Rickets, Osteoporosis)', 9, 40, 'Orthopedic Diseases'],
  [12, 'Arthritis (OA, RA, Gout)', 9, 40, 'Orthopedic Diseases'],
  [12, 'Congenital Anomalies (CTEV, DDH)', 9, 35, 'Orthopedic Diseases'],
  [12, 'Avascular Necrosis & Osteochondritis', 8, 30, 'Orthopedic Diseases'],

  // OPHTHALMOLOGY (subject 13)
  [13, 'Anatomy & Physiology of Eye', 8, 30],
  [13, 'Optics & Refraction', 10, 40, 'Anatomy & Physiology of Eye'],
  [13, 'Diseases of Eye', 10, 60],
  [13, 'Conjunctiva (Conjunctivitis, Trachoma)', 10, 45, 'Diseases of Eye'],
  [13, 'Cornea (Ulcers, Keratitis, Dystrophies)', 10, 50, 'Diseases of Eye'],
  [13, 'Lens (Cataract & Surgery)', 10, 55, 'Diseases of Eye'],
  [13, 'Glaucoma', 10, 50, 'Diseases of Eye'],
  [13, 'Uveal Tract (Uveitis)', 9, 40, 'Diseases of Eye'],
  [13, 'Retina (DR, ARMD, Detachment)', 10, 55, 'Diseases of Eye'],
  [13, 'Neuro-Ophthalmology', 9, 45, 'Diseases of Eye'],
  [13, 'Squint & Ocular Motility', 9, 40, 'Diseases of Eye'],
  [13, 'Eyelids, Orbit & Lacrimal System', 8, 35, 'Diseases of Eye'],
  [13, 'Community Ophthalmology', 8, 30, 'Diseases of Eye'],

  // ENT (subject 14)
  [14, 'Ear', 10, 60],
  [14, 'Diseases of External Ear', 8, 30, 'Ear'],
  [14, 'Diseases of Middle Ear (ASOM, CSOM)', 10, 50, 'Ear'],
  [14, 'Diseases of Inner Ear (Vertigo, Meniere\'s)', 9, 45, 'Ear'],
  [14, 'Audiology & Deafness', 9, 40, 'Ear'],
  [14, 'Facial Nerve Disorders', 9, 35, 'Ear'],
  [14, 'Nose & PNS', 9, 50],
  [14, 'Rhinitis & Sinusitis', 9, 40, 'Nose & PNS'],
  [14, 'Nasal Polyps & Epistaxis', 9, 35, 'Nose & PNS'],
  [14, 'Tumors of Nose & PNS', 8, 35, 'Nose & PNS'],
  [14, 'Throat (Pharynx & Larynx)', 10, 60],
  [14, 'Tonsils & Adenoids', 9, 40, 'Throat (Pharynx & Larynx)'],
  [14, 'Pharyngeal Abscesses & Tumors', 9, 40, 'Throat (Pharynx & Larynx)'],
  [14, 'Laryngeal Disorders (Vocal Cords, Stridor)', 9, 45, 'Throat (Pharynx & Larynx)'],
  [14, 'Carcinoma Larynx', 10, 50, 'Throat (Pharynx & Larynx)'],
  [14, 'Dysphagia & Esophagus', 8, 35, 'Throat (Pharynx & Larynx)'],

  // PSYCHIATRY (subject 15)
  [15, 'General Psychiatry', 9, 40],
  [15, 'Psychopathology & MSE', 10, 40, 'General Psychiatry'],
  [15, 'Psychopharmacology', 10, 45, 'General Psychiatry'],
  [15, 'Clinical Disorders', 10, 60],
  [15, 'Schizophrenia & Psychotic Disorders', 10, 50, 'Clinical Disorders'],
  [15, 'Mood Disorders (Depression, Bipolar)', 10, 50, 'Clinical Disorders'],
  [15, 'Anxiety, OCD & Stress Disorders', 10, 45, 'Clinical Disorders'],
  [15, 'Substance Use Disorders (Alcohol, Opioids)', 10, 55, 'Clinical Disorders'],
  [15, 'Somatoform & Dissociative Disorders', 8, 35, 'Clinical Disorders'],
  [15, 'Personality Disorders', 9, 35, 'Clinical Disorders'],
  [15, 'Child Psychiatry (ADHD, Autism)', 9, 40, 'Clinical Disorders'],
  [15, 'Sleep & Eating Disorders', 8, 30, 'Clinical Disorders'],

  // DERMATOLOGY (subject 16)
  [16, 'Basics of Dermatology', 8, 30],
  [16, 'Skin Lesions & Histopathology', 8, 30, 'Basics of Dermatology'],
  [16, 'Skin Infections', 10, 50],
  [16, 'Bacterial Infections (Pyoderma, TB, Leprosy)', 10, 50, 'Skin Infections'],
  [16, 'Fungal Infections', 9, 40, 'Skin Infections'],
  [16, 'Viral Infections', 9, 35, 'Skin Infections'],
  [16, 'Parasitic Infections (Scabies, Pediculosis)', 8, 30, 'Skin Infections'],
  [16, 'Papulosquamous Disorders', 9, 45],
  [16, 'Psoriasis & Lichen Planus', 10, 45, 'Papulosquamous Disorders'],
  [16, 'Eczema & Dermatitis', 9, 40, 'Papulosquamous Disorders'],
  [16, 'Vesiculobullous Disorders', 9, 45],
  [16, 'Pemphigus & Pemphigoid', 10, 45, 'Vesiculobullous Disorders'],
  [16, 'STD & Leprosy', 10, 50],
  [16, 'Sexually Transmitted Diseases', 10, 50, 'STD & Leprosy'],
  [16, 'Connective Tissue Diseases (SLE, Scleroderma)', 8, 35, 'STD & Leprosy'],
  [16, 'Pigmentary Disorders & Appendages', 8, 35, 'STD & Leprosy'],

  // RADIOLOGY (subject 17)
  [17, 'General Radiology', 9, 40],
  [17, 'X-ray & Radiation Physics', 8, 35, 'General Radiology'],
  [17, 'CT & MRI Basics', 9, 35, 'General Radiology'],
  [17, 'USG & Doppler', 8, 30, 'General Radiology'],
  [17, 'Contrast Media', 9, 30, 'General Radiology'],
  [17, 'Systemic Radiology', 9, 50],
  [17, 'Chest Radiology', 10, 45, 'Systemic Radiology'],
  [17, 'GIT & Abdominal Radiology', 9, 40, 'Systemic Radiology'],
  [17, 'Musculoskeletal Radiology', 9, 35, 'Systemic Radiology'],
  [17, 'Neuroradiology', 9, 40, 'Systemic Radiology'],
  [17, 'Radiotherapy & Nuclear Medicine', 8, 40],

  // ANESTHESIA (subject 18)
  [18, 'General Anesthesia', 9, 50],
  [18, 'Pre-anesthetic Evaluation', 8, 35, 'General Anesthesia'],
  [18, 'Intravenous Anesthetics', 9, 40, 'General Anesthesia'],
  [18, 'Inhalational Anesthetics', 9, 40, 'General Anesthesia'],
  [18, 'Muscle Relaxants', 9, 35, 'General Anesthesia'],
  [18, 'Airway Management & Equipment', 10, 45, 'General Anesthesia'],
  [18, 'Regional Anesthesia', 9, 45],
  [18, 'Spinal & Epidural Anesthesia', 10, 45, 'Regional Anesthesia'],
  [18, 'Local Anesthetics', 9, 35, 'Regional Anesthesia'],
  [18, 'Critical Care & Resuscitation', 9, 45],
  [18, 'CPR & BLS/ACLS', 10, 45, 'Critical Care & Resuscitation'],
  [18, 'Oxygen Therapy & Monitoring', 8, 35, 'Critical Care & Resuscitation'],
];

