import { StyleSheet } from 'react-native';
import { linearTheme as n } from '../../theme/linearTheme';
import { errorAlpha } from '../../theme/colorUtils';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: n.colors.background },
  safeWarn: { backgroundColor: n.colors.errorSurface },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: n.spacing.lg,
    paddingTop: 20,
  },
  backBtn: { padding: 4 },
  backText: { color: n.colors.error, fontSize: 16, fontWeight: '700' },
  headerTitle: {
    color: n.colors.textPrimary,
    fontWeight: '900',
    fontSize: 17,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  placeholder: { width: 60 },
  scroll: { flex: 1 },
  content: { padding: n.spacing.lg, paddingBottom: 60 },

  hostageInfo: {
    padding: n.spacing.lg,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  hostageText: { color: n.colors.textSecondary, flex: 1, fontSize: 13, lineHeight: 18 },

  timerBox: {
    alignItems: 'center',
    borderRadius: 20,
    padding: n.spacing.xl,
    marginBottom: n.spacing.xl,
  },
  timerBoxWarn: {
    borderWidth: 2,
    borderColor: n.colors.error,
  },
  timerLabel: {
    color: n.colors.textSecondary,
    fontSize: 12,
    marginBottom: 6,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  timer: {
    color: n.colors.textPrimary,
    fontWeight: '900',
    fontSize: 52,
    fontVariant: ['tabular-nums'],
  },
  timerWarn: { color: n.colors.error },

  proofOfLifeBox: {
    backgroundColor: n.colors.errorSurface,
    borderRadius: 20,
    padding: n.spacing.xl,
    marginBottom: n.spacing.xl,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: n.colors.error,
    position: 'relative',
    overflow: 'hidden',
  },
  proofOfLifeBoxActive: {
    // Additional glow effect via shadow
  },
  proofIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: `${n.colors.error}22`,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: n.spacing.lg,
    position: 'relative',
  },
  proofPulseRing: {
    position: 'absolute',
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: errorAlpha['40'],
  },
  proofTitle: {
    color: n.colors.error,
    fontWeight: '900',
    fontSize: 20,
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: 1,
  },
  proofSub: {
    color: n.colors.warning,
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
  },
  proofTimerContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  proofTimerCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: n.colors.errorSurface,
    borderWidth: 3,
    borderColor: n.colors.error,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  proofTimerText: {
    color: n.colors.textPrimary,
    fontSize: 36,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  proofTimerTextUrgent: {
    color: n.colors.error,
  },
  proofTimerLabel: {
    color: n.colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  proofWarning: {
    color: n.colors.textPrimary,
    fontSize: 13,
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 18,
    maxWidth: '90%',
  },

  subjectSection: { marginBottom: 20 },
  sectionLabel: {
    color: n.colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  subjectGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  subjectChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    backgroundColor: n.colors.card,
  },
  subjectChipText: { fontWeight: '700', fontSize: 13, lineHeight: 18 },
  selectedSubject: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: n.spacing.lg,
    padding: n.spacing.lg,
    borderRadius: 12,
  },
  selectedSubjectText: { color: n.colors.textPrimary, fontWeight: '800', fontSize: 16 },
  changeBtn: { color: n.colors.accent, fontSize: 14, fontWeight: '700' },

  transcribeBtn: {
    backgroundColor: n.colors.card,
    padding: n.spacing.lg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: n.colors.border,
    marginBottom: 12,
    alignItems: 'center',
  },
  transcribeBtnActive: {
    backgroundColor: n.colors.errorSurface,
    borderColor: n.colors.error,
  },
  transcribeBtnText: { color: n.colors.accent, fontWeight: '800', fontSize: 14 },
  importTranscribeBtn: { marginTop: -4 },

  noteSection: { marginBottom: 20 },
  noteInput: {
    borderRadius: 12,
    padding: n.spacing.lg,
    color: n.colors.textPrimary,
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.card,
    marginBottom: 12,
  },
  noteInputWarn: {
    backgroundColor: n.colors.errorSurface,
    borderColor: n.colors.error,
    borderWidth: 2,
  },
  noteInputActive: {
    borderColor: n.colors.success,
    borderWidth: 2,
  },
  saveBtn: {
    backgroundColor: n.colors.accent,
    borderRadius: 12,
    padding: n.spacing.lg,
    alignItems: 'center',
  },
  saveBtnDisabled: { backgroundColor: n.colors.border },
  saveBtnWarn: { backgroundColor: n.colors.error },
  saveBtnText: {
    color: n.colors.textPrimary,
    fontWeight: '800',
    fontSize: 16,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },

  breakTriggerBtn: { padding: n.spacing.lg, alignItems: 'center', marginTop: 8 },
  breakTriggerText: { color: n.colors.textSecondary, fontWeight: '700', fontSize: 14 },

  savedNotes: { marginTop: 8 },
  noteRow: {
    flexDirection: 'row',
    marginBottom: 8,
    backgroundColor: n.colors.card,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  noteDot: {
    color: n.colors.accent,
    fontSize: 20,
    marginRight: 8,
    lineHeight: 22,
    fontWeight: '900',
  },
  noteText: { color: n.colors.textPrimary, fontSize: 14, flex: 1, lineHeight: 22 },

  resumeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: n.colors.background,
  },
  resumeTitle: {
    color: n.colors.textPrimary,
    fontSize: 24,
    fontWeight: '800',
    marginBottom: n.spacing.lg,
  },
  resumeTimer: { color: n.colors.accent, fontSize: 80, fontWeight: '900', marginBottom: 40 },
  resumeBtn: {
    backgroundColor: n.colors.accent,
    borderRadius: 16,
    paddingHorizontal: 40,
    paddingVertical: n.spacing.lg,
  },
  resumeBtnText: { color: n.colors.textPrimary, fontWeight: '800', fontSize: 18 },
  proofWarnBanner: {
    backgroundColor: `${n.colors.warning}12`,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: n.colors.warning,
    marginBottom: 12,
  },
  proofWarnText: {
    color: n.colors.warning,
    fontWeight: '700',
    fontSize: 13,
    textAlign: 'center',
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: n.colors.error,
  },
});
