import { StyleSheet } from 'react-native';
import { linearTheme as n } from '../../theme/linearTheme';
import { blackAlpha, whiteAlpha, captureFillAlpha, captureBorderAlpha } from '../../theme/colorUtils';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: n.colors.background },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: n.colors.surface,
    margin: 16,
    marginBottom: 8,
    borderRadius: 12,
    paddingHorizontal: 14,
    minHeight: 52,
    paddingVertical: 8,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
    color: n.colors.textPrimary,
    minHeight: 24,
    paddingVertical: 0,
  },
  overviewCard: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 10,
  },
  overviewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: n.spacing.md,
  },
  overviewCopy: {
    flex: 1,
  },
  overviewEyebrow: {
    letterSpacing: 1.1,
  },
  overviewTitle: {
    marginTop: n.spacing.xs,
  },
  overviewText: {
    marginTop: n.spacing.xs,
  },
  overviewPill: {
    backgroundColor: n.colors.primaryTintSoft,
    borderRadius: n.radius.full,
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  overviewMetricsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: n.spacing.md,
  },
  overviewMetricCard: {
    flexGrow: 1,
    minWidth: 110,
    backgroundColor: n.colors.background,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  overviewMetricValue: {
    marginBottom: 2,
  },
  overviewMetricLabel: {
    lineHeight: 16,
  },
  toolbarCard: {
    marginHorizontal: 16,
    marginBottom: 10,
  },
  statsBar: {
    paddingBottom: 8,
  },
  statsText: { color: n.colors.textMuted, fontSize: 13 },
  selectionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  selectionText: { color: n.colors.textPrimary, fontSize: 14, fontWeight: '700' },
  selectionActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  selectionCancelBtn: { paddingHorizontal: 10, paddingVertical: 6 },
  selectionCancelText: { color: n.colors.textMuted, fontSize: 13, fontWeight: '600' },
  selectionDeleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: n.colors.error,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  selectionDeleteText: { color: n.colors.textPrimary, fontSize: 12, fontWeight: '700' },
  listContent: { paddingHorizontal: 16, paddingBottom: 80 },
  loadMoreBtn: {
    alignItems: 'center',
    paddingVertical: 14,
    marginHorizontal: 16,
    marginBottom: 24,
    borderRadius: 12,
    backgroundColor: n.colors.accent + '12',
    borderWidth: 1,
    borderColor: n.colors.accent + '30',
  },
  loadMoreText: {
    color: n.colors.accent,
    fontSize: 14,
    fontWeight: '700',
  },
  sortBar: { flexDirection: 'row', paddingVertical: 8, gap: 8 },
  sortBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.surface,
  },
  sortBtnActive: {
    borderColor: n.colors.accent,
    backgroundColor: n.colors.accent + '22',
  },
  sortBtnText: { color: n.colors.textMuted, fontSize: 13, fontWeight: '600' },
  sortBtnTextActive: { color: n.colors.accent, fontWeight: '700' },
  filterBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingBottom: 8,
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.surface,
  },
  filterChipActive: {
    borderColor: n.colors.accent,
    backgroundColor: n.colors.accent + '22',
  },
  filterChipText: { color: n.colors.textSecondary, fontSize: 12, fontWeight: '600' },
  filterChipTextActive: { color: n.colors.accent, fontWeight: '700' },

  noteCard: {
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
  },
  noteCardSelected: {
    borderWidth: 1,
    borderColor: n.colors.accent,
    backgroundColor: n.colors.primaryTintSoft,
  },
  selectionTickWrap: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 2,
  },
  noteHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  subjectChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexShrink: 1,
  },
  dateText: {
    color: n.colors.textMuted,
    fontSize: 12,
    lineHeight: 16,
    flexShrink: 1,
    marginLeft: 'auto',
    textAlign: 'right',
    minWidth: 72,
  },
  appBadge: { color: n.colors.textMuted, fontSize: 11, marginBottom: 6 },
  summaryText: { color: n.colors.textPrimary, fontSize: 15, lineHeight: 22, marginBottom: 10 },
  summaryPreviewText: {
    color: n.colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 10,
  },
  statusRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  statusBadge: {
    backgroundColor: n.colors.surface,
    color: n.colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 10,
    overflow: 'hidden',
  },
  statusBadgeWarn: {
    backgroundColor: `${n.colors.warning}18`,
    color: n.colors.warning,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 10,
    overflow: 'hidden',
  },
  noteFooter: {},
  topicsRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8 },
  topicPill: {
    backgroundColor: n.colors.surface,
    color: n.colors.textSecondary,
    fontSize: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    marginRight: 6,
    marginBottom: 4,
    overflow: 'hidden',
  },
  moreBadge: { color: n.colors.textMuted, fontSize: 11, marginLeft: 4, alignSelf: 'center' },
  metaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  metaText: { color: n.colors.textMuted, fontSize: 12, lineHeight: 18 },
  confidenceBadge: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    color: n.colors.textPrimary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
  },

  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingBottom: 100,
  },
  emptyTitle: { color: n.colors.textPrimary, fontSize: 18, fontWeight: '600', marginTop: 16 },
  emptySubtitle: { color: n.colors.textMuted, fontSize: 14, textAlign: 'center', marginTop: 8 },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: blackAlpha['85'],
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
    flex: 0,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: n.colors.border,
  },
  modalTitle: {
    color: n.colors.textPrimary,
    fontSize: 18,
    fontWeight: '600',
    flex: 1,
    lineHeight: 24,
  },
  modalHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 8, marginLeft: 10 },
  headerActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  headerActionText: { color: n.colors.accent, fontSize: 12, fontWeight: '600' },
  modalScroll: { padding: 16, flexGrow: 1 },
  modalMeta: { marginBottom: 16 },
  customTitleText: {
    color: n.colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  modalMetaText: { color: n.colors.textSecondary, fontSize: 13 },
  renameCard: {
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  renameLabel: {
    color: n.colors.textSecondary,
    fontSize: 12,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  renameInput: {
    backgroundColor: n.colors.surface,
    borderWidth: 1,
    borderColor: n.colors.border,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: n.colors.textPrimary,
    fontSize: 15,
  },
  renameActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 10 },
  renameCancelBtn: { paddingHorizontal: 12, paddingVertical: 8 },
  renameCancelText: { color: n.colors.textMuted, fontSize: 13, fontWeight: '600' },
  renameSaveBtn: {
    backgroundColor: captureFillAlpha['14'],
    borderWidth: 1,
    borderColor: captureBorderAlpha['24'],
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  renameSaveText: { color: n.colors.textPrimary, fontSize: 13, fontWeight: '700' },
  modalSection: { marginBottom: 20 },
  modalSectionTitle: {
    color: n.colors.textSecondary,
    fontSize: 12,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  managerActionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  managerActionBtn: {
    minWidth: '46%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: whiteAlpha['14'],
    backgroundColor: whiteAlpha['6'],
  },
  managerActionBtnDisabled: {
    opacity: 0.55,
  },
  managerActionText: {
    color: n.colors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    flexShrink: 1,
  },
  studyNoteCard: {
    borderRadius: n.radius.lg,
    paddingHorizontal: n.spacing.lg,
    paddingVertical: n.spacing.md,
  },
  modalText: { color: n.colors.textMuted, fontSize: 15, lineHeight: 22 },
  topicsWrap: { flexDirection: 'row', flexWrap: 'wrap' },
  topicPillLarge: {
    backgroundColor: n.colors.surface,
    color: n.colors.textPrimary,
    fontSize: 13,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    marginRight: 8,
    marginBottom: 8,
    overflow: 'hidden',
  },
  transcriptText: {
    color: n.colors.textSecondary,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Inter_400Regular',
    padding: 12,
    borderRadius: 8,
  },
  transcriptCard: {
    borderRadius: 8,
  },
  selectionModeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: n.colors.accent + '22',
    borderBottomWidth: 1,
    borderBottomColor: n.colors.accent + '55',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  selectionModeBannerText: { color: n.colors.accent, fontSize: 13, fontWeight: '600' },
  selectionModeCancelText: { color: n.colors.accent, fontSize: 13, fontWeight: '800' },
  headerSearchRight: { marginTop: 0 },
  readerOpenBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: n.colors.accent + '18',
  },
  readerOpenText: { color: n.colors.accent, fontSize: 12, fontWeight: '700' },
  readerContainer: { flex: 1, backgroundColor: n.colors.background },
  readerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: n.colors.border,
  },
  readerCloseBtn: { padding: 6, marginRight: 8 },
  readerHeaderTitle: {
    flex: 1,
    color: n.colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 22,
  },
  readerCopyBtn: { padding: 8 },
  readerScroll: { flex: 1 },
  readerScrollContent: { padding: 20, paddingBottom: 60 },
  loadingState: { alignItems: 'center', justifyContent: 'center', padding: 48, flex: 1 },
  loadingText: { color: n.colors.textMuted, fontSize: 14, marginTop: 16 },
});
