import { StyleSheet } from 'react-native';
import { linearTheme as n } from '../../theme/linearTheme';
import {
  whiteAlpha,
  blackAlpha,
  errorAlpha,
  captureFillAlpha,
  captureBorderAlpha,
} from '../../theme/colorUtils';

export const settingsStyles = StyleSheet.create({
  flex: { flex: 1 },
  safe: { flex: 1, backgroundColor: n.colors.background },
  settingsShell: {
    flex: 1,
    flexDirection: 'row',
  },
  settingsMain: {
    flex: 1,
    minWidth: 0,
  },
  content: { padding: n.spacing.lg, paddingBottom: 60, alignItems: 'center' },
  contentInner: {
    width: '100%',
    maxWidth: 1040,
  },
  mobileCategoryScroller: {
    marginBottom: n.spacing.md,
  },
  mobileCategoryNav: {
    gap: 8,
    paddingRight: n.spacing.sm,
  },
  mobileCategoryButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.surface,
  },
  mobileCategoryButtonActive: {
    borderColor: n.colors.borderHighlight,
    backgroundColor: n.colors.primaryTintSoft,
  },
  shellSummaryCard: {
    marginTop: 0,
  },
  categoryContent: {},
  categoryStack: {
    gap: n.spacing.lg,
  },
  summaryCard: {
    marginTop: n.spacing.sm,
    marginBottom: n.spacing.lg,
    borderRadius: 24,
    overflow: 'hidden',
  },
  summaryCardCompact: {
    marginBottom: n.spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: n.spacing.md,
  },
  summaryCopy: {
    flex: 1,
  },
  summaryEyebrow: {
    letterSpacing: 1.1,
  },
  summaryTitle: {
    marginTop: n.spacing.xs,
  },
  summaryText: {
    marginTop: n.spacing.xs,
    maxWidth: 560,
  },
  summaryPill: {
    backgroundColor: n.colors.primaryTintSoft,
    borderRadius: n.radius.full,
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  summaryMetricsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: n.spacing.md,
  },
  summaryMetricCard: {
    flexGrow: 1,
    minWidth: 110,
    flexBasis: 140,
    backgroundColor: n.colors.background,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summaryMetricValue: {
    marginBottom: 2,
  },
  summaryMetricLabel: {
    lineHeight: 16,
  },
  aiRouteCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
    backgroundColor: n.colors.surface,
    padding: n.spacing.lg,
    marginBottom: n.spacing.md,
  },
  aiRouteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  aiRouteIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: n.colors.primaryTintSoft,
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
  },
  aiRoutePath: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginTop: n.spacing.md,
  },
  aiRouteNode: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.background,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  aiRouteNodePrimary: {
    borderColor: n.colors.borderHighlight,
    backgroundColor: n.colors.primaryTintSoft,
  },
  title: {
    color: n.colors.textPrimary,
    fontSize: 26,
    fontWeight: '900',
    marginBottom: 20,
    marginTop: 8,
  },
  section: {
    marginBottom: n.spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.surface,
    overflow: 'hidden',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: n.spacing.lg,
    paddingVertical: 14,
    minHeight: 68,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: n.spacing.md,
    flex: 1,
  },
  sectionIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  sectionTitle: {
    color: n.colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  categoryLabel: {
    color: n.colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginTop: n.spacing.xl,
    marginBottom: n.spacing.sm,
  },
  sectionContent: {
    borderRadius: 0,
    borderTopWidth: 1,
    borderTopColor: n.colors.border,
    padding: n.spacing.lg,
    backgroundColor: whiteAlpha['1.5'],
  },
  label: { color: n.colors.textSecondary, fontSize: 13, marginBottom: 6, marginTop: 8 },
  input: {
    backgroundColor: n.colors.background,
    borderRadius: 10,
    padding: 12,
    color: n.colors.textPrimary,
    fontSize: 14,
    borderWidth: 1,
    borderColor: n.colors.border,
    marginBottom: 4,
  },
  apiKeyCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.background,
    padding: 12,
    marginBottom: 10,
  },
  apiKeyCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 10,
  },
  apiKeyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  apiKeyGridItem: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 310,
    minWidth: 0,
  },
  apiKeyToolbar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 14,
  },
  apiKeyFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    flex: 1,
  },
  apiKeyFilterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.background,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  apiKeyFilterChipActive: {
    borderColor: n.colors.borderHighlight,
    backgroundColor: n.colors.primaryTintSoft,
  },
  apiKeyValidateAllBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
    backgroundColor: n.colors.card,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  apiKeyEmptyState: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: n.colors.border,
    backgroundColor: n.colors.background,
    padding: n.spacing.lg,
  },
  apiKeyRow: { flexDirection: 'row', alignItems: 'center', gap: 8, width: '100%' },
  apiKeyRowStacked: { flexDirection: 'column', alignItems: 'stretch' },
  apiKeyInput: { flex: 1, minWidth: 0, marginBottom: 0 },
  inputSuccess: { borderColor: n.colors.success },
  inputError: { borderColor: n.colors.error },
  validateBtn: {
    backgroundColor: n.colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 52,
    flexShrink: 0,
    borderWidth: 1,
    borderColor: n.colors.borderLight,
  },
  validateBtnWide: {
    width: '100%',
    minHeight: 46,
  },
  validateBtnSuccess: {
    backgroundColor: n.colors.successSurface,
    borderColor: n.colors.success,
  },
  validateBtnError: { backgroundColor: n.colors.errorSurface, borderColor: n.colors.error },
  validateBtnOk: {
    backgroundColor: n.colors.successSurface,
    borderColor: n.colors.success,
  },
  validateBtnFail: {
    backgroundColor: n.colors.errorSurface,
    borderColor: n.colors.error,
  },
  validateBtnTesting: { backgroundColor: n.colors.card, borderColor: n.colors.accent },
  validateBtnText: { color: n.colors.textPrimary, fontWeight: '700', fontSize: 14 },
  validationMsg: { fontSize: 12, marginTop: 6, marginBottom: 2 },
  validationSuccess: { color: n.colors.success },
  validationError: { color: n.colors.error },
  hint: { color: n.colors.textMuted, fontSize: 12, marginBottom: 4 },
  subSectionPanel: {
    backgroundColor: n.colors.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  subSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: n.spacing.sm,
    minHeight: 34,
  },
  subSectionHeaderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  subSectionAccent: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: n.colors.accent,
  },
  subSectionLabel: {
    color: n.colors.accent,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  subSectionBody: {
    paddingTop: 10,
  },
  subSectionDivider: {
    height: 1,
    backgroundColor: n.colors.border,
    marginVertical: 12,
  },
  localModelBtn: {
    marginTop: 12,
    flexDirection: 'row',
    backgroundColor: n.colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: n.colors.border,
    padding: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  localModelBtnText: { color: n.colors.textPrimary, fontWeight: '700', fontSize: 14 },
  localAiStatusText: {
    color: n.colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  localAiStatusRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  localAiStatusTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  localAiEnabledHint: {
    color: n.colors.success,
    marginBottom: 8,
  },
  localAiWarningHint: {
    color: n.colors.warning,
    marginTop: 4,
  },
  localAiModelName: {
    color: n.colors.warning,
    fontWeight: '700',
  },
  localAiModelMissing: {
    color: n.colors.textMuted,
    fontWeight: '600',
  },
  localAiActiveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: n.colors.success,
    marginLeft: 12,
    flexShrink: 0,
  },
  localAiCard: {
    marginTop: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: n.colors.border,
    borderRadius: 12,
    backgroundColor: n.colors.background,
  },
  localAiCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  localAiCardLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  localAiCardIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  localAiBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: n.colors.success + '22',
  },
  localAiBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: n.colors.success,
  },
  localAiBadgeWarning: {
    backgroundColor: n.colors.warning + '22',
  },
  localAiBadgeWarningText: {
    color: n.colors.warning,
  },
  localAiBadgeMuted: {
    backgroundColor: n.colors.textMuted + '22',
  },
  localAiBadgeMutedText: {
    color: n.colors.textMuted,
  },
  autoFetchBtn: {
    marginTop: 10,
    backgroundColor: n.colors.card,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
  },
  autoFetchBtnDisabled: { opacity: 0.5 },
  autoFetchBtnText: { color: n.colors.accent, fontSize: 13, fontWeight: '600' },
  switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  switchLabel: {
    color: n.colors.textPrimary,
    fontWeight: '600',
    fontSize: 15,
    marginBottom: 2,
  },
  testBtn: {
    marginTop: 12,
    backgroundColor: n.colors.card,
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: n.colors.borderHighlight,
  },
  testBtnText: { color: n.colors.accent, fontWeight: '600', fontSize: 14 },
  providerRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    backgroundColor: n.colors.surface,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 4,
  },
  providerIndex: {
    color: n.colors.textMuted,
    fontSize: 13,
    width: 20,
    lineHeight: 20,
    fontWeight: '600' as const,
  },
  providerDot: { width: 8, height: 8, borderRadius: 4, marginRight: 10 },
  providerName: { flex: 1, fontSize: 14, lineHeight: 20, fontWeight: '500' as const },
  providerActions: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 6,
    marginLeft: 8,
    justifyContent: 'flex-end' as const,
  },
  providerActionBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: n.colors.background,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  providerActionBtnDisabled: { opacity: 0.25 },
  providerActionBtnPressed: { backgroundColor: n.colors.card },
  saveBtn: {
    backgroundColor: captureFillAlpha['14'],
    borderWidth: 1,
    borderColor: captureBorderAlpha['24'],
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row' as const,
    marginTop: 8,
  },
  saveBtnDisabled: { opacity: 0.5 },
  saveBtnText: { color: n.colors.textPrimary, fontWeight: '800', fontSize: 17 },
  backupRow: { flexDirection: 'row', gap: 10, marginTop: 8 },
  backupBtn: {
    flex: 1,
    backgroundColor: whiteAlpha['6'],
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: whiteAlpha['14'],
  },
  backupBtnText: { color: n.colors.accent, fontWeight: '700', fontSize: 14 },
  backupDate: {
    color: n.colors.textMuted,
    fontSize: 11,
    textAlign: 'center',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  frequencyRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    marginBottom: 4,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  frequencyChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: n.colors.background,
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  frequencyChipActive: {
    backgroundColor: n.colors.borderHighlight,
    borderColor: n.colors.accent,
  },
  frequencyChipText: {
    fontSize: 13,
    color: n.colors.textMuted,
    fontWeight: '500',
  },
  frequencyChipTextActive: {
    color: n.colors.accent,
    fontWeight: '700',
  },
  guruMemoryInput: {
    minHeight: 88,
    paddingTop: 12,
  },
  liveModelsRefreshRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  modelChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
    marginBottom: 8,
  },
  freqBtn: {
    backgroundColor: n.colors.background,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: n.colors.border,
  },
  freqBtnActive: {
    backgroundColor: n.colors.primaryTintSoft,
    borderColor: n.colors.accent,
  },
  freqText: { color: n.colors.textSecondary, fontSize: 12, fontWeight: '600' },
  freqTextActive: { color: n.colors.accent, fontWeight: '700' },
  footer: {
    color: n.colors.borderLight,
    fontSize: 11,
    textAlign: 'center',
    marginTop: 24,
    lineHeight: 18,
  },
  chipGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  typeChip: {
    backgroundColor: n.colors.background,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: n.colors.border,
    flexDirection: 'row',
    alignItems: 'center',
  },
  typeChipBlocked: {
    backgroundColor: n.colors.errorSurface,
    borderColor: errorAlpha['8'],
  },
  typeChipLocked: { borderColor: n.colors.borderHighlight, opacity: 0.5 },
  typeChipText: { color: n.colors.textPrimary, fontSize: 13, fontWeight: '600' },
  typeChipTextBlocked: { color: n.colors.error },
  typeChipX: { color: n.colors.error, fontSize: 11 },
  clearBtn: { marginTop: 10, padding: 10, alignItems: 'center' },
  clearBtnText: { color: n.colors.textMuted, fontSize: 13 },
  maintenanceBtn: {
    marginTop: 10,
    backgroundColor: whiteAlpha['6'],
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: whiteAlpha['14'],
  },
  maintenanceBtnText: { color: n.colors.textPrimary, fontWeight: '700', fontSize: 14 },
  dangerBtn: {
    backgroundColor: n.colors.errorSurface,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: n.colors.error,
  },
  dangerBtnText: { color: n.colors.accent, fontWeight: '700', fontSize: 14 },
  modelSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: n.colors.background,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: n.colors.border,
    marginBottom: 8,
  },
  modelSelectorText: { color: n.colors.textPrimary, fontSize: 14, fontWeight: '600' },
  modelSelectorArrow: { color: n.colors.textMuted, fontSize: 12 },
  modalOverlay: {
    flex: 1,
    backgroundColor: blackAlpha['82'],
    justifyContent: 'flex-end',
  },
  modalContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '60%',
  },
  modalTitle: {
    color: n.colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: n.spacing.lg,
    textAlign: 'center',
  },
  modelItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: n.colors.borderLight,
  },
  modelItemActive: {
    backgroundColor: n.colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 0,
  },
  modelItemText: { color: n.colors.textSecondary, fontSize: 15 },
  modelItemTextActive: { color: n.colors.accent, fontWeight: '700' },
  checkMark: { color: n.colors.accent, fontWeight: 'bold' },
  closeBtn: {
    marginTop: n.spacing.lg,
    padding: 14,
    alignItems: 'center',
    backgroundColor: n.colors.border,
    borderRadius: 12,
  },
  closeBtnText: { color: n.colors.textPrimary, fontWeight: '600' },
  permRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: n.colors.border,
  },
  permLabel: { color: n.colors.textPrimary, fontSize: 14, fontWeight: '600' },
  permStatus: { fontSize: 12, marginTop: 2 },
  permOk: { color: n.colors.success },
  permError: { color: n.colors.error },
  fixBtn: {
    backgroundColor: n.colors.primaryTintSoft,
    borderWidth: 1,
    borderColor: n.colors.accent,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  fixBtnText: { color: n.colors.accent, fontSize: 12, fontWeight: '800' },
  diagBtn: { marginTop: 12, alignItems: 'center', padding: 10 },
  diagBtnText: { color: n.colors.textMuted, fontSize: 13, textDecorationLine: 'underline' },
  dropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    backgroundColor: n.colors.background,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: n.colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 6,
    marginBottom: 8,
  },
  dropdownValue: {
    color: n.colors.textPrimary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    flex: 1,
  },
  dropdownArrow: { color: n.colors.textMuted, fontSize: 16, marginLeft: 8 },
  dropdownBackdrop: {
    flex: 1,
    backgroundColor: blackAlpha['60'],
    justifyContent: 'center',
    padding: 24,
  },
  dropdownSheet: {
    borderRadius: 16,
    paddingVertical: 12,
    maxHeight: '80%',
  },
  dropdownSheetTitle: {
    color: n.colors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: n.colors.border,
  },
  dropdownGroupLabel: {
    color: n.colors.accent,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  dropdownItemActive: { backgroundColor: n.colors.primaryTintSoft },
  dropdownItemText: { color: n.colors.textPrimary, fontSize: 14, lineHeight: 20, flex: 1 },
  dropdownItemTextActive: { color: n.colors.accent, fontWeight: '700' },
  dropdownCheck: { color: n.colors.accent, fontSize: 16, fontWeight: '700', marginLeft: 8 },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    marginTop: 4,
  },
  settingRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: n.spacing.md,
    flex: 1,
  },
});

export type SettingsStyles = typeof settingsStyles;
